### ISSUE TITLE
"Call running" notification when making a call

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1018]
Is this really necessary?  What purpose does it serve?

The problem I have with it is that it obscures the top row of numbers on the number pad such that one has to fumble in a panic (or just wait, if one can) to get rid of it so that one can enter number prompts the call receiver might want.

**Comment by Viish** [comment]
The "Call running" notification is sent to a low importance channel, so it shouldn't "pop-up". On what device/android did you had the issue?

We use it as "service notification" to keep the service alive during a call (for that it needs to be "foreground" and for that it needs a visible notification) to ensure the app stays alive during a call.

**Comment by brianjmurrell** [comment]
> The "Call running" notification is sent to a low importance channel, so it shouldn't "pop-up". On what device/android did you had the issue?

It happens on my Huawei Honor 8 running 8.0.0.  I tried my LineageOS device running Android 9 and indeed it doesn't pop up there.

Here's what the notification configuration screen of my Honor 8 shows:

![Screenshot_20200520-071110](https://user-images.githubusercontent.com/559317/82439798-42babf80-9a69-11ea-96d2-71db4cae78c8.jpg)

On my LineageOS device, the _MyLinphone service notification_ shows _Behaviour: Show silently_ which is probably why it doesn't do what the Honor 8 is doing.  Yeah.  If I change that one to _Make sound and pop up on screen_ it behaves like the Honor 8.

Presumably I should be able to make the Honor 8 behave the same.  The notifications configuration screen for the _MyLinphone service notification_ on the Honor 8 is a little less straightforward than the LineageOS device:

![Screenshot_20200520-071918](https://user-images.githubusercontent.com/559317/82440539-819d4500-9a6a-11ea-9ea4-31d88192a35f.jpg)

Disabling _Banners_ seems to have made it stop popping up when the call is initiated.

I noticed that even once I disabled _Banners_, it was still _chirping_ at the start of the call and I had to disable _Ringtone_ also.

Is this default notifications setting something that Linphone is supposed to be configuring itself and failing on the Honor 8?  It seems like probably that is the case given that it's behaving as expected on a more _stock_ Android like LineageOS.

--------

As an aside it's interesting that there is both _MyLinphone instant messages notifications_  and _Linphone instant messages notifications_.  Both of my devices show that.  Seems like somewhere is not picking up the change:

```patch
--- a/app/src/main/res/values/strings.xml
+++ b/app/src/main/res/values/strings.xml
@@ -1,7 +1,7 @@
 <?xml version='1.0' encoding='UTF-8'?>
 
 <!DOCTYPE resources [
-    <!ENTITY appName "Linphone">
+    <!ENTITY appName "MyLinphone">
 ]>
 
 <resources>
```

--------

As yet another aside, I was noticing that when I passed my finger over the camera, the screen blacks out.  I guess that's intentional, and it typically supposed to happen when the phone is put up against one's ear?  As neat as that is, it does need to make trying to pull down the notification shade while the phone is still in front of one as one's finger typically passes over the camera in the effort to pull down the notification shade.

**Comment by Viish** [comment]
Yes, default settings for each notification channels are defined in the app.
However we can't specify each setting you see. Instead we set the "importance" of the notifications of each channel. For the service notification we use "LOW". I guess Huawei has defined it's own notification settings for the "LOW importance" that aren't the same as stock Android or Samsung's, but at least you have a UI to change that.

Regarding the Linphone mention instead of MyLinphone, I checked and the entity is correctly used. Maybe a side effect of the update from a previous version (if the channel exists it isn't re-created, so if the name has changed in the meantime it won't be applied). Uninstall & reinstall the app should fix that.

Finally, yes, the proximity sensor prevents the ear from interacting with the screen, and can be triggered by the finger above the proximity sensor (not necessary the front cam). But the width of the screen is large enough for you to be able to pull the status bar without puttin your finger above the sensor.
