### ISSUE TITLE
XmlRpc request

### ISSUE THREAD

**Issue by cradle1001** [BelledonneCommunications/linphone-android#1023]
Is it possible to create custom XmlRpc request? How can?
Because I can't find the XmlRpc Helper in the master.

**Comment by Viish** [comment]
Indeed the XmlRpcHelper class doesn't exists anymore as we didn't use it, but you can still checkout it from an old version it should still work.

Otherwise you can use our XmlRpc API directly using core.createXmlRpcSession(url) that will return a XmlRpcSession object.
Then create a request with session.createRequest(returnType, methodName) and add some parameters if needed (request.addStringArg or request.addIntArg) and a listener (request.addListener). Then send the request on the session with session.sendRequest(request). 
If you need the response it will be available on the request object : getContent(), getIntResponse(), getRawResponse(), getStringResponse() and getStatus().
Finally release the session using session.release().
