### ISSUE TITLE
Dark UI theme

### ISSUE THREAD

**Issue by msva** [BelledonneCommunications/linphone-android#105]
Can you please implement a simple minimalistic Dark theme for Linphone app?
I guess it can even be a "negative" version of current theme (light -> dark, orange -> cyan, ...).

// Well, actually, it would be nice to have dark theme also in desktop app too

**Comment by DatBewar** [comment]
Hello,
It's not in our future feature list so for the moment i can't tell you if it will be done or not.

**Comment by lolfinger** [comment]
because
protected void toggleSpeaker() {
  isSpeakerEnabled = !isSpeakerEnabled;
  if (LinphoneManager.getLc().getCurrentCall() != null) {
   LinphoneManager.getInstance().enableProximitySensing(!isSpeakerEnabled);
  }
  if (isSpeakerEnabled) {
   LinphoneManager.getInstance().routeAudioToSpeaker();
   **speaker.setImageResource(R.drawable.speaker_selected);**
   LinphoneManager.getLc().enableSpeaker(isSpeakerEnabled);
  } else {
   Log.d("Toggle speaker off, routing back to earpiece");
   LinphoneManager.getInstance().routeAudioToReceiver();
   **speaker.setImageResource(R.drawable.speaker_default);**
  }
 }

this is not a good idea with Java code

**Comment by msva** [comment]
@Viish, can you elaborate a bit about closing the issue, please?

**Comment by Viish** [comment]
The code handling the icons has been improved in coming release, but we do not plan to have a dark mode.

**Comment by Viish** [comment]
Dark mode has been added in next to come release 4.1

**Comment by arigit** [comment]
In MacOS, using 4.1.1, there is no dark theme or any theme to be chosen (Preferences > User Interface = no options for theme)

**Comment by Viish** [comment]
If you are talking about MacOS version (desktop app) indeed there is no dark theme.
Dark theme is currently only available on Android.

**Comment by Penguin-Guru** [comment]
For the record, the desktop client is painful for me to look at. I probably won't be able to use it unless there is a way to change this.
