### ISSUE TITLE
Read registration status

### ISSUE THREAD

**Issue by mihabogataj-eurotronik** [BelledonneCommunications/linphone-android#1079]
Hi, I am struggling to retrieve registration status. I use the following line: `LinphoneManager.getInstance().getAccountCreator().isAccountActivated()`

This line always returns "RequestFailed", but linphone calls still work. I don't know where to start looking for solution. Any help would be greatly appreciated.

**Comment by Viish** [comment]
Hi,
If you have already configured your account (ProxyConfig object) then you should check the proxy config state instead of the account creator (only used to created/configure accounts).
You can use the following pseudo code:
core.getDefaultProxyConfig().getState() == ProxyConfig.RegistrationStateOk

**Comment by mihabogataj-eurotronik** [comment]
It works like a charm, thank you!
