### ISSUE TITLE
ECHO

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-android#1092]
Hi,

Ask a few questions about echo：
1，Why do we detect the echo? If not, will there always be echo during the talking?
2,  I find that echo detection often fails. When, or what state in the code, is it appropriate to get the echo?
3，If echo check fails, will it be good for call quality if I write a default value to the following interface? If so, what default values do you think is better? For example, the default value is 400, as follows: LinphonePreferences.instance ().setEchoCalibration(400);

thanks

**Comment by Viish** [comment]
If you detect echo with the echo canceller calibration or the echo tester, then yes you will probably hear some echo during a call.

If echo calibration fails, check the speaker is enabled when doing so, otherwise it won't work. It can also be the result of a hardware echo canceller.

Finally no, you can't set any value and hope it will work for the echo canceller calibration. Each device has a correct value that differs, hence the calibration process.

**Comment by fengqz627** [comment]
When the echo is calibrated, my speaker is on, because I hear that the calibration sound will be sent out after calibration, but many calibration failed.

**Comment by fengqz627** [comment]
Is the echo calibration value related to the environment of the equipment or only to the equipment. For example, if a device is placed in one place and gets an echo value, will the echo value change if it is placed in another place?

**Comment by Viish** [comment]
No, the place where you calibrate the echo canceller isn't relevant.
Also make sure the volume is maxed out.
