### ISSUE TITLE
Is there a way to avoid "+" in gradle dependencies? or warnings should be just ignored ?

### ISSUE THREAD

**Issue by KhaverDmytro** [BelledonneCommunications/linphone-android#1160]
Hello, so with the latest updates you use it like this:  implementation "org.linphone:linphone-sdk-android:4.5+"

But Android docs do not suggest using "+" and warn about with this message:
Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds
(org.linphone:linphone-sdk-android:4.5.0-alpha.96+7e045e7) -> here I also tried to build using specific latest sdk release, but it still has "+" in it

**Comment by Viish** [comment]
Hi,

Yes we are using '+' even if discouraged by Google because we use it to build nightly version of both app + latest SDK.
We also use it in releases to ensure hot fixes are available.

However you can safely remove it when you want to stick to a specific release tag, for example 4.4.1. This can be usefull to ensure the SDK doesn't change if you are satisfied with the version you have.

Cheers,
