### ISSUE TITLE
connection is disconnected automatically

### ISSUE THREAD

**Issue by fang123123** [BelledonneCommunications/linphone-android#1187]
Hi,
I am facing a problem, connection is disconnected automatically. I check logs and find this:
2020-10-08 12:00:45.046 I/: Call [0x8fed6d4c]: Media connectivity with sip:xx is lost, call is going to be terminated
I wonder what could cause it?
thanks

**Comment by Viish** [comment]
Hi,
This happens when your device hasn't received audio from the remote during a call for a certain amount of time (default is 30secs).
You can change this value or disable it using the "nortp_timeout" property of the [rtp] section of the configuration or using linphone_core_set_nortp_timeout().
Cheers,
