### ISSUE TITLE
What is purpose of these property

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1201]
Hello @Viish ,

Please tell me the use of following default properties : 

1) ping_with_options
2) keepalive_period
3) tunnel=disabled

Thanks,

**Comment by Viish** [comment]
Hi,

1. Here's it's doc: `/* Defer the start of the call after the OPTIONS ping for outgoing call or send an option request back to the caller so that we get a chance to discover our nat'd address before answering for incoming call */`
2. As the name indicates, it is the period at which keep alive packets will be sent
3. It indicates the tunnel is disabled. Tunnel is a proprietary module we developed to bypass SIP packets being filtered in some countries.

Next time you have a question like that, please grep in the liblinphone repository to find the answer.

**Comment by amit1576** [comment]
Hi @Viish ,

Thanks and Next time I will check repository.
