### ISSUE TITLE
address.setPort()

### ISSUE THREAD

**Issue by MuYiC** [BelledonneCommunications/linphone-android#1234]
It doesn't work that I invoke Address.setPort(9060); I grap bag that shows Destination Port:5060

**Comment by MuYiC** [comment]
> It doesn't work that I invoke Address.setPort(9060); I grap bag that shows Destination Port:5060
`   if (address == null){
            //address = core.createAddress("10.10.0.29:5060");
            //address = Factory.instance().createAddress("sip:linphone@10.10.0.29:5888");
            address = core.interpretUrl("sip:linphone@10.10.0.29");
            address.setPort(5888);
        }

        if (address == null) return;

        if (chatRoom == null){
            chatRoom = core.getChatRoomFromUri(address.asStringUriOnly());
        }
        ChatMessage chatMessage = chatRoom.createEmptyMessage();
        chatMessage.addUtf8TextContent("type :" + type + "code:" + code);

    
        if (chatMessage.getContents().length > 0) {
            chatMessage.send();
        }`

**Comment by Viish** [comment]
A few things:

- you can do directly `address = core.interpretUrl("sip:linphone@10.10.0.29:5888");`
- `getChatRoomFromUri` interprets url, so you can do `chatRoom = core.getChatRoomFromUri("sip:linphone@10.10.0.29:5888");`
- is is likely your issue is due to the `address.asStringUriOnly()` that may remove the port. You can try with `address.asString()`

**Comment by MuYiC** [comment]
> * "sip:linphone@10.10.0.29:5888"
thanks first
I try to do like your reply,but still is 5060

**Comment by Viish** [comment]
Please attach logs from SDK

**Comment by MuYiC** [comment]
[linphone2.log](https://github.com/BelledonneCommunications/linphone-android/files/5640194/linphone2.log)
this is the logs
