### ISSUE TITLE
Linphone android is not taking language

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#1321]
Hello,
Linphone android is not taking default lanaguage, suppose my phone language is russian and it's not taking by default russian. Can you please tell me what the issue ?

Thanks

**Comment by Viish** [comment]
Hi,
Sorry no I don't know why this happens, we rely on the Android OS internationalization system which automatically selects the best language if available, English otherwise, but Russian is part of the 4.3.1 release currently deployed to the Play Store.
Do you have a LineageOS or other custom OS ? Are you getting our app from another source or building it yourself?
Cheers,
