### ISSUE TITLE
registration state not stable

### ISSUE THREAD

**Issue by Cullian2017** [BelledonneCommunications/linphone-android#1322]
we are using Linphone SDK 4.4.0 for our project.

we are using the UDP protocal to connect to the proxy, we found the registration state is not stable, even with very good internet, the APP failed to connect to the proxy very often to make the call.

**Comment by Viish** [comment]
Hi,
UDP isn't a reliable protocol, and even on a reliable network packets may get lost. Also some routers are doing work on SIP UDP packets (SIP ALG), which will cause issues, cf [our wiki page about this](https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Good%20practices%20for%20using%20SIP/).
We strongly advise you to use TCP or even better TLS instead of UDP.
Cheers,

**Comment by Cullian2017** [comment]
Hi Viish,

Thank for your prompt response.

In case the proxy server only supports UDP, what can I do to improve the stability?
Can I increase the MTU from default value 1300 to 1400? And configure the codecs only support G.711 and G.G29?

**Comment by Viish** [comment]
Also disable push notifications as the push token is quite long.

**Comment by Cullian2017** [comment]
Is there any API can I use to get the SIP packet size？ Then I can know if the connection failure was caused by this issue？

**Comment by Viish** [comment]
Not that I know of, no.

**Comment by Cullian2017** [comment]
Hi Viish,

if disable push notifications will cause other issues or not?

**Comment by Viish** [comment]
> if disable push notifications will cause other issues or not?

As you are using your own proxy, it isn't capable of sending push notification to our app anyway, so no.
Otherwise yes, push notifications are the best way to ensure receiving calls & messages instantaneously.
