### ISSUE TITLE
Google Play store rejected Application for violating their Malicious Behavior or User Data policy

### ISSUE THREAD

**Issue by arpit-it** [BelledonneCommunications/linphone-android#135]
Hello there, 
I am using Linphone - android as the base for one of the project.
The version of Linphone I am using is 
**versionCode="2599"**

When I tried to put the application on playstore, **Google Play Developer rejected the application** providing the following reason:

_This app uses software that contains security vulnerabilities for users or allows the collection of user data without proper disclosure._

Vulnerability | APK Version(s)
-- | --
Portable SDK for UPnP DevicesThe vulnerabilities were fixed in libupnp v1.6.18 and higher. For more information and next steps, please see this [article](https://support.google.com/faqs/answer/6346109). | 2599

In research for the solution regarding this issue, I found that the latest version of Linphone Android doesn't have this vulnerability.

My question is that **is there a way to fix this issue in the version of Linphone that I am using** as it will take huge efforts to perform upgrade. Or you can **suggest an easier way to update the internal libraries without affecting the newly added activities and other classes**.

**Comment by uditb** [comment]
@DatBewar  Hi,
Please help on this.

**Comment by DatBewar** [comment]
Hello,
I don't know how help you with this problem,
2599 is a very old version of Linphone(currently 3.2.8)

**Comment by astuter** [comment]
Hello, @arpit-it,

You have to update native libraries of linphone in order to get your apk approved by Google. 

Que) is there a way to fix this issue in the version of Linphone that I am using?
Ans:- Not sure, mostly not without help of original developers.

Que)  can you suggest an easier way to update the internal libraries without affecting the newly added activities and other classes? 
Ans:- Try simply replacing your native libraries with latest binaries, If it works fine or not. If not, than you also have to update linphonecore and source code in your project.

**Comment by CVeniamin** [comment]
@DatBewar, I think @arpit-it  got that wrong since `versionCode="2599"` refers to his own app not linphone.
I followed @astuter advice and built linphone-android from scratch then run `$make liblinphone-android-sdk` to generate binary files, i.e., `.so` files which I use them on my android project. 

Nevertheless, the issue wasn't resolved and it persists to this day. I had a look at previous commits regarding upnp and found only this one https://github.com/BelledonneCommunications/linphone-android/commit/6a855e6b4b6d1b0e2cf0de085ba02e7093e445c5 which doesn't show much information if in fact was fixed but can only speculate based on commit message. 
It would be nice if from someone from Belledonne team is capable of telling that I'm doing something wrong or linphone-android still uses `libupnp version prior to 1.6.18` when building liblinphone android sdk.
