### ISSUE TITLE
Issue reading certificates in Android 11

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1357]
I'm currently trying to get TLS working with the kotlin branch.

`04-13 08:30:50.758 29316 29316 I UZ Linphone: Trying to connect to [TLS://X.X.X.X:443]
04-13 08:30:50.760  7510  9066 E MediaProvider: Couldn't find file: /storage/emulated/0/linphone/linphoneca.pem
04-13 08:30:50.760 29316 29316 E UZ Linphone: Failed to load root ca from /sdcard/linphone/linphoneca.pem: PK - Read/write of file failed`

I'm guessing this has something to do with the scoped storage restrictions that were introduced in Android 11? Is there a workaround for this except for adding the pem files to the assets directory?

**Comment by Viish** [comment]
`linphoneca.pem` isn't a file handled by us, so it is your job to properly package it and install it.
We only handle the `rootca.pem` generated in the linphone-sdk that you can edit if you build your own SDK.
Otherwise you will have to rely on the [core.setRootCa()](http://linphone.org/snapshots/docs/liblinphone/5.0/java/org/linphone/core/Core.html#setRootCa-java.lang.String-) API.

**Comment by driesken** [comment]
Yes, I'm aware of that but this issue also prevents the possibility to use "client_cert_chain" and "client_cert_key" which would point to certificates on the external storage?

**Comment by Viish** [comment]
As long as you grant the right permissions you should be able with the right code to read a file on the external storage.
