### ISSUE TITLE
Chat Message sending failed when other party is not connected to server

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1361]
Hello @Viish ,

While sending message from A to B. 
Case 1 : Message sent successfully if B is Registered on server or App is in Front.
Case 2 : Message sending Failed when B is not registered on server or he is not connected to internet at that moment.
This message comes in Case2 : 
    SIP/2.0 405 Method Not Allowed
    Via: SIP/2.0/TLS 192.168.232.2:41564;branch=z9hG4bK.Sxb2aodZq;rport=63883;received=122.160.221.52

Both party is connected over TLS.

Please find logs. 
In one log message sending failed to B, When App of B not in front.
Second logs when message sent successfully to B, when App of B is in Front.

[ChatMessageSent.txt](https://github.com/BelledonneCommunications/linphone-android/files/6322970/ChatMessageSent.txt)
[ChatMessageNotFailed.txt](https://github.com/BelledonneCommunications/linphone-android/files/6322971/ChatMessageNotFailed.txt)

**Comment by Viish** [comment]
Hi,

This is a proxy server matter. As a client we send the request to the server, he's the one that answers if a message (or a call) can be made or not.
And if you think about it, it's normal that if the recipient of a call or message is not known (which happens when a device is not registered), the server notifies you that it can't do it.
There is a difference between being registered but not connected and not being registered.

Cheers,

**Comment by amit1576** [comment]
> This is a proxy server matter. As a client we send the request to the server, he's the one that answers if a message (or a call) can be made or not.

Ok, got it. Proxy server give 405 response as on TLS the registration removed as soon as the client de-register. 
I guess as chat is not stored anywhere so when B party even register after he will not able to see any message from A.

**Comment by Viish** [comment]
> I guess as chat is not stored anywhere so when B party even register after sometime, he will not able to see any message from A.

That's the job of the server. And it can only do it as long as B is registered (even if not connected). When a client unregisters (sends a Register with expires=0), it means the server must forgot about it completely. Hence message is not saved until it connects again.
That's why in our app/SDK we never unregister unless explicitely asked.
