### ISSUE TITLE
All Calls Paused when Telephony [Manager] Phone state is ringing

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#1364]
Hello @Viish ,

I had set setCallGsmON(false); on [Manager] Phone state is ringing. But still all APP calls get paused. This was working fine in last SDK, I guess.

Please find attached logs.

[AllCallPaused_TelephonyRinging.txt](https://github.com/BelledonneCommunications/linphone-android/files/6336164/AllCallPaused_TelephonyRinging.txt)

**Comment by Viish** [comment]
Hi,

Yes this is due to a new feature that was introduced in 4.5 SDK. Now we automatically handle the Android Audio Focus during a call, and when that focus is lost (like when a GSM call is made or received), we automatically pause all calls like we should when audio focus is lost.
If you want to disable this behavior, set the following in your factory config file:
```
[audio]
android_pause_calls_when_audio_focus_lost=0
```

Cheers,
