### ISSUE TITLE
Unable to reply to chats on Android app

### ISSUE THREAD

**Issue by mcv110** [BelledonneCommunications/linphone-android#1376]
**Describe the bug**
Unable to reply to incoming messages on Android app. Able to send messages without issue. 

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Incoming message is received
2. Tap on the message
3.  type a response and click the send (paper airplane button)
4. message does not send
5.  create a new message via the "search contact button"
6.  select a contact
7.  type a message and click send, message sends.

**Expected behavior**
I expected a response to send.

**Please complete the following information**
 - Device: Samsung Note 4
 - OS: Android 6
 - Version of the App: 4.3.1
 - Version of the SDK 4.4.2

**SDK logs**
https://www.linphone.org:444//tmp/6089c3ec2f495_c026f1609497e06dd287.gz 

**Adb logcat logs**
N/A - no app crash

**Comment by Viish** [comment]
Hi,

Issue seems to be related to the IP you send the message to.
When it's `10.45.1.43:5060` it's always failing, either by a `480 Temporarily not available` or a `403 Denied`, and when it's `10.45.0.83:5060` it's fine.

So problem is when you reply you send the message directly to the IP of the device that has sent it instead of the IP of your server.
This happens because you aren't using a domain name, and in the received message the FROM header doesn't contains the right IP (but it is right in the CONTACT header).
To fix that change your proxy server config so the IP in the FROM would be the right one (your server's one and not the sender's one).

Cheers,
