### ISSUE TITLE
SMS disappeared in conversation view for incoming SMS with Voip.ms service

### ISSUE THREAD

**Issue by jane8dow** [BelledonneCommunications/linphone-android#1386]
Sorry, I read a past post regarding this issue but it did not resolve my issue. 

From the previous post, it stated to make the following changes:
setting hide_chat_rooms_from_removed_proxies=0    in     /data/data/org.linphone/files/.linphonerc 

But the direcory "org.linphone" does not exist on my Pixel 4a phone. It is because my phone is not rooted? 

Is there another way to fix this? I'm using voip.ms service. TIA.

**Comment by Viish** [comment]
If you have installed the app from the Store you can't have access to org.linphone as the app is not "debuggable" in release mode.

If you have installed the app from Android Studio the package name is org.linphone.debug instead of org.linphone but you should be able to access it. 
But a better way would be to change the value in the factory rc file before building & installing the app.

Anyway regarding your issue there is a visual parameter for that in the Chat section of the Settings.

Cheers,

**Comment by jane8dow** [comment]
Thanks for the quick replied.  Not a techie here. If possible could point me to a quick source on building the app with Android Studio. TIA.

**Comment by Viish** [comment]
Simply download the project (either using http or git), open Android Studio and open the project and click build while your device is plugged in.
