### ISSUE TITLE
Camera doesn't work when build a bundle 

### ISSUE THREAD

**Issue by paruyrs** [BelledonneCommunications/linphone-android#1443]
There is blank (black) screen when you try open camera for example qr scanner when build ad bundle. APK is working

**Comment by Viish** [comment]
We use AppBundle for a while now, we never had such issue.
Can you enable debug logs in advanced settings, restart the app, open the QR code view to reproduce and then upload logs please? Then copy/paste the link to the logs here.

**Comment by paruyrs** [comment]
[https://file.io/tcOWemyfPM4k](url)

**Comment by Viish** [comment]
It says deleted...

**Comment by paruyrs** [comment]
https://wetransfer.com/downloads/239116ecf8ecb3db39437a038211aec320210706143435/93b8b3d25310f7b66c843bed6791625d20210706143446/4f4b09

**Comment by Viish** [comment]
This is because of this:
`ERROR Couldn't find field PLUGINS_ARRAY in org.linphone.core.BuildConfig`

It seems you have built a SDK but weirdly: linphone-sdk branch doesn't match liblinphone submodule version. And because the linphone-sdk branch you use is very old (4.2), I guess it doesn't have the changes in build.gradle to create the array: https://github.com/BelledonneCommunications/linphone-sdk/blob/master/cmake/Android/gradle/build.gradle.cmake#L93

My recomendation is for you to checkout latest release branch (release/4.5), update submodules (git submodule update) and build a clean & up-to-date SDK.
