### ISSUE TITLE
IAX/IAX2 support

### ISSUE THREAD

**Issue by reg3xp** [BelledonneCommunications/linphone-android#1496]
Add IAX/IAX2 support

**Comment by Viish** [comment]
No, we are only doing SIP.

**Comment by slesru** [comment]
No support for IAX2 is bad thing.

**Comment by Viish** [comment]
@slesru, 
First of all thanks for such a useful comment...
Second we aren't related to Asterisk nor we are using it, so we don't need it.

**Comment by slesru** [comment]
IAX2 is open standard, so anybody can implement it.
If you don't want, no problem.

**Comment by Viish** [comment]
> If you don't want, no problem, I don't use linphone anyway.

If you don't use it, why posting such comment? Why do you care?

**Comment by slesru** [comment]
I'd like to have alternative to zoiper.

**Comment by slesru** [comment]
I see, you don't want IAX2,  but ready to get money :-)

**Comment by Viish** [comment]
We don't want IAX2 because it doesn't fit in our plans for our products.
However, as a company that needs to live, we offer development of features for client that are ready to pay for.
That's because we do sell such development that we are able to offer a quality open-source SIP SDK / client & server.

**Comment by slesru** [comment]
OK, thank you. Unfortunately, I'm afraid we can't pay for development, not because we have no money, but because we are from Russia , you know current situation :-( This is also reason why I am looking for open source client, although we are quite happy with zoiper, but who knows will it work during nuclear war? ;-)
