### ISSUE TITLE
Can't call previous incoming calls from history

### ISSUE THREAD

**Issue by yennor** [BelledonneCommunications/linphone-android#1527]
**Describe the bug**
When I try to call a previously incoming call from history, I can't make the call. It tells me "Service unavailable or network error".
I think the problem could be, that incomin calls are shown as "sip:079xxxxxxxx@c4-mgc.vtx" while when I dial a number (outgoing call), it is shown as "sip:079xxxxxxxxxxx@s1.303...ch". And previously outoing calls in the history, I can dial directly from the history again. The url shown for outgoing calls is with the server, where my sip account is registered. 
I guess a possible solution would be to give the option, to save numbers, without the server, but only the phone number.

**To Reproduce**
1. Go to history
2. Click on an incoming call and try to dial it

**Expected behavior**
One should be able to dial previously incoming calls. Right now I always have to dial the number by hand, for the call to work

**Please complete the following information**
 - Device: Poco X3
 - OS: Android 11
 - Version of the App 4.5.2
 - Version of the SDK ??

**Comment by Viish** [comment]
Thanks for the logs.

Indeed calling back from history fails because Linphone can't resolve the domain name `c4-mgc.vtx` that is used in the FROM identity when you receive a call instead of the proxy domain `s1.303189.bus.ipvoip.ch`.

Can you reach out to them to explain the issue? 
Also note that the TO header in the INVITE is also wrong as it contains your IP as domain instead of your SIP identity.

**Comment by vtx-team** [comment]
Good afternoon
Thanks for raising this issue, I am Marc Leurent, one of the VoIP Engineer at VTX and I did check this problem ( I also use Linphone on my Debian Desktop :-) for test purpose )

* ** Information:**
- The from header SIP URI domain depends on the source of the caller, the domain could be a valid FQDN or not
- We do only allowed registered users to pass outgoing calls via the proxy where the user is connected

* **Problem**: here indeed the caller SIP URI domain is not matching any DNS entry ( c4-mgc.vtx )

* **Solution** : On the SIP account settings, below the SIP proxy setup, enable the outbound proxy setup to force all calls to be routed via the proxy. After doing this, you will be able to call back the caller ( cf screenshot below )

* **Additional Info** : While doing test, I did cope with another problem, we need to wait the 2nd registration of the account to be able to pass any outgoing calls to have our SBC Audiocodes learning the new Contact entry with the public IP instead of the private one from 1st REGISTER. It would be hidden by disabling rport feature on the client but I do not see how to disable this on Linphone. Going to see if it is a SBC Audiocodes bug or if it is something to report to linphone in another ticket

@yennor 
1) Could you please enable the outbound proxy, switch to UDP mode and wait 30s, then everything should work, even calling back these numbers

@Viish 
1) Thanks for the report too, do you know if we could disable the rport feature in linphone not to have it learning his public IP, it is not needed. My problem is that the SBC is learning the 1st Contact header with the private IP and won't update it until next REGISTER CSeq, so outgoing calls won't work between 1st and 2nd REGISTER

Thanks and Best Regards
Marc Leurent

![image](https://user-images.githubusercontent.com/93672354/140325322-d4589e76-ec25-4025-9ddc-ecaac5dd08d7.png)

**Comment by yennor** [comment]
@vtx-team Thanks for your quick reply. I've tried your suggestion for a few days, and it seems to work stable and solved the problem :-)

**Comment by Viish** [comment]
@vtx-team 

> do you know if we could disable the rport feature in linphone not to have it learning his public IP

Yes, you can. In the linphonerc config file, simply set the following:
```
[sip]
use_rport=0
```

**Comment by vtx-team** [comment]
@yennor : Thanks for the feedback, glad to hear it 
@Viish : Thanks for the reply

**Actions**
1)  We did test use_rport=0 on debian and indeed it doesn't sent it anymore. Unfortunately, the SBC on our side enforces it, so linphone learns it and use it on 2nd REGISTER after 401 and SBC keep the 1st local IP in memory until next REGISTER so outgoing calls are stuck in the meantime, we are checking it with SBC Audiocodes provider "S.mon 96164 - SBC - Linphone - Bug on SBC or Linphone ?" 

**Information**
- On Bria I remember the REGISTER flow, and it learns public IP with the rport indeed, but keep using initial contact to finish 1st REGISTRATION process, then unregister old contact with private IP and switch to the 1st one. So we are not coping with this problem

**Next Steps**
1) We need to check if it is compliant with RFC to switch Contact IP in the middle of a REGISTER transaction
2) Checking ticket "S.mon 96164 - SBC - Linphone - Bug on SBC or Linphone ?"  with our provider



Best Regards

Marc Leurent
