### ISSUE TITLE
Firebase disabled   

### ISSUE THREAD

**Issue by ilaoQ** [BelledonneCommunications/linphone-android#158]
![image](https://user-images.githubusercontent.com/21697771/32835227-4991deac-ca40-11e7-8596-a0f43dd5d622.png)

What's going on here?

**Comment by DatBewar** [comment]
Hello,
it's just saying that you aren't place the google-services.json for the firebase push notification.

**Comment by JoeDD** [comment]
Thanks，Would you like me to download it manually and configure it?, where do I get it?

**Comment by JoeDD** [comment]
hello  ![image](https://user-images.githubusercontent.com/21697771/32874875-dbdccaee-cacf-11e7-94b8-abf236d2d31d.png)
Does it take a long time?

**Comment by JoeDD** [comment]
![image](https://user-images.githubusercontent.com/21697771/32878040-53050e42-cadf-11e7-9dbe-3347681cbc7a.png)

![image](https://user-images.githubusercontent.com/21697771/32878068-67f19d02-cadf-11e7-9459-0560cf049fc6.png)
Can xulrunner take the place of ia32-libs?The system I use is centos7 64 bit

**Comment by DatBewar** [comment]
No the build is not so long.
For your second question i don't understand what's your problem

**Comment by JoeDD** [comment]
Thankyou，the second problem has been solved。
![image](https://user-images.githubusercontent.com/21697771/32931632-2aa75222-cba0-11e7-94a9-43fe2f46bb71.png)  
and it still takes a long time,Is it because of the google-services configuration problem?
![image](https://user-images.githubusercontent.com/21697771/32931689-9439b4fa-cba0-11e7-9581-3e0307d2ed00.png)
![image](https://user-images.githubusercontent.com/21697771/32931703-a37271be-cba0-11e7-8481-9ff9a968e3e8.png)
