### ISSUE TITLE
LinPhone declines calls on ChromeOS

### ISSUE THREAD

**Issue by ricardokuznik** [BelledonneCommunications/linphone-android#1612]
**LinPhone declines calls with 486 - busy here**
When calling a SIP client, there is only the message of a missed call, LinPhone itself is not ringing. Problem was told me today the first time.  
PBX gets SIP reponse "486 - busy here", but LinPhone is not busy.

**Please complete the following information**
 - Device: [Acer Chromebook 315 (CB315)]
 - OS: [e.g. ChromeOS 97.0.4692.102]
 - Version of the App LinphoneAndroid/4.6.0 
 - Version of the SDK [LinphoneSDK/5.1.0]

**SDK logs**
https://www.linphone.org:444//tmp/620a59cc380a3_de493ed14ec3ac8c8f55.gz

**Comment by Viish** [comment]
Hi,

This happens because Telecom Manager API tells us that incoming call isn't permitted.
I don't know yet if this is expected because you are using a Chrome OS device or if the reason is valid.

Anyway in the meantime you can disable the "improve bluetooth devices interaction" setting in the "Call" parameters to workaround this issue.

Cheers,

**Comment by ricardokuznik** [comment]
Awesome, that's it - thanks a lot.

BTW ... can Linphone send busy, when busy ? We always receive calls when we already have a call.

**Comment by Viish** [comment]
Set the max_call property in your linphonerc to 1: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/release/4.6/app/src/main/assets/linphonerc_default#L34

**Comment by ricardokuznik** [comment]
I'll take a look! 
Thank you!!!!
