### ISSUE TITLE
Incoming call: Display local called number / SIP account

### ISSUE THREAD

**Issue by xxorax** [BelledonneCommunications/linphone-android#1694]
I ssuccessfully setup OVH SIP account on LinPhone and it works well once some settings about running the app in background and disabling battery optimisation have been set.

However I face a major issue : on an incoming call, we do not see the called number or SIP account (our own number), so we don't know if the call come from LinPhone or from the simcard for example.

Maybe it's an issue of the Android Phone app ? In this case is there any settings to change ?

Thanks

**Comment by Viish** [comment]
Hi,

I guess you are on Android 12 or newer?
Starting Android 12 we use the "native call style" for call notifications, but indeed that may generate some confusion regarding whether it's a SIP or TEL call.
Sadly there is nothing (yet) in Android framework to be able to distinguish between the two...
I suggest you to either click on the incoming call notification to display the incoming call activity (you'll be able to distinguish between the native dialer and linphone) or to use the linphone-android ringtone instead of your device's default one (in Call settings).

Cheers,

**Comment by xxorax** [comment]
> I guess you are on Android 12 or newer?

That's it.

> Sadly there is nothing (yet) in Android framework to be able to distinguish between the two...

It's sad... I was runnning CSipSimple App long time ago, the integration was much more evolved than Android permit now (SIP call in Phone App, etc...)

> I suggest you to either click on the incoming call notification to display the incoming call activity (you'll be able to distinguish between the native dialer and linphone) 

I guess this works only when your screen is ON (= you are using it). For the calls when the screen if OFF, I see no way to get this information quickly...

>or to use the linphone-android ringtone instead of your device's default one (in Call settings).

Nice trick ! I guess it will work like this.

Thanks !

**Comment by Viish** [comment]
If the screen is off, you won't see the notification and you will directly see the incoming call view for either our app or your native dialer, so you won't have this issue at all.

**Comment by xxorax** [comment]
My bad, the SIP account had a configuration mistake, making a redirection to the simcard number... so opening the Android Phone app instead of LinPhone... sorry.

We can see clearly that the called SIP account when LinPhone show up (not the notification).
Tested on Android 11 and Android 12.

When the screen is ON, the call notification(where you can answer) does not displayed the called SIP account (tested in Android 12), but it display well the caller (name + number)
Not an issue for me.

Thanks
