### ISSUE TITLE
Does linphone support calling multiple SIP accounts at the same time?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-android#1743]
Does linphone support calling multiple SIP accounts at the same time? Not in the form of conference.

**Comment by Viish** [comment]
Why would you call multiple people at once if it wasn't to make a conference?

**Comment by August1023** [comment]
What I want to achieve is to call multiple SIP accounts at once. If a sip account is not online (404), I can call it repeatedly until the SIP account is online.

**Comment by Viish** [comment]
> What I want to achieve is to call multiple SIP accounts at once. If a sip account is not online (404), I can call it repeatedly until the SIP account is online.

I'm sorry but I don't understand how calling multiple SIP accounts at once helps you achieve that ?

**Comment by August1023** [comment]
Sorry, I'm wrong. It's not necessarily the same time. Can the same SIP account call other SIP accounts in the process of calling a certain SIP account?

**Comment by Viish** [comment]
You can make a call during another call if that's what you're asking.
If the second call is answered the first one will be paused as you can only have one active call at all times (unless it's a conference).

**Comment by August1023** [comment]
Can multiple accounts ring together when they are not connected?

**Comment by Viish** [comment]
I still don't understand.
If an account isn't registered on a proxy server it can't ring as it is not reachable

**Comment by August1023** [comment]
The scenario I want to implement is as follows. There is one calling account AAA and two called accounts BBB and CCC. AAA calls BBB and CCC, but CCC is not online. At this time, the BBB will ring and the CCC will return to 404. What I want to do is that while the BBB rings, AAA calls CCC again. If CCC goes online at this time, BBB and CCC will ring together.

**Comment by Viish** [comment]
You can't make two outgoing calls at the same time, so no you can't.

**Comment by jaroslawsky** [comment]
I have to disagree. I am using two instances (processes) of linphonec with one registered proxy. In the two instances running at the same time, two different numbers can be called with the same proxy. Both phones are ringing simultaneously.
We use the whole thing to alert both my wife and myself via cell phone in the event of an alarm from the smoke detectors.
For this our Fritzbox is configured with a LAN phone as a SIP server. The LAN phone is configured to a phone number that is not otherwise used. In our cell phones, this number is set with the name "Smoke Alarm" and a loud ringtone.
