### ISSUE TITLE
Calls Drop

### ISSUE THREAD

**Issue by OfficialGitCub** [BelledonneCommunications/linphone-android#1820]
Hello Linphone Team!

Calls seem to be dropping after about 33 seconds - 45 seconds. 

1. **Describe the bug** (mandatory)
Calls placed from Linphone app to regular cellular/voip  phone number end unexpectedly. After about 33 seconds the call seems to disband. 

2. **To Reproduce** (mandatory)

Place call on Sip account. 

3. **Expected behavior** (mandatory)

The call remains active until either parties end call.

4. **Please complete the following information** (mandatory)

 - Device: Pixel 6
 - OS: GrapheneOS
 - Version of the App 5.0.0
 - Version of the SDK ? Utilizing SIP . not sure
 - Where you did got it from F Droid

**Comment by Viish** [comment]
Hi,

A call can be automatically terminated if the app detects no audio has been received for 30 seconds (then it considers the call as broken and hangs up).
When that's the case it is almost always because of a network issue. Ensure you have turned on STUN & ICE in your account settings.

If issue persists after having done that, please attach debug logs and I'll reopen the issue.

**Comment by OfficialGitCub** [comment]
Hi @Viish  - it seems as if this feature (to drop calls after 30 seconds) inhibits a user from completing a call after a contact to an automated service which directs a call that will ring after transfer. Is it possible to open this ticket as an improvement and elect to have this turned off/on?

**Comment by Viish** [comment]
Hi, No there is no reason it would prevent that.
Do you have logs from the app when it happens?

**Comment by OfficialGitCub** [comment]
@Viish - This may be happening due to connection to mobile network. I'll turn on logs and conduct further testing. If I am not mistaken I am getting a 403 error. More info to come.
