### ISSUE TITLE
OutGoing Call Fail with Request Timeout 408

### ISSUE THREAD

**Issue by Ptitg** [BelledonneCommunications/linphone-android#1835]
Hello

Since version 5.0.0, all outgoing calls fail with "Request Timeout 408". (It worked with versions 4.6.x.)
Incoming calls works.

 - Device: Sony Xperia XZ2
 - OS: Android 11 and 12
 - Version of the App: 5.0.0 and 5.0.2
 - From F-Droid
 - Variant [/e/OS](https://e.foundation/)
 - Sip provider : OVH

**Comment by Viish** [comment]
Hi, 

Please attach logs showing the issue.

Cheers,

**Comment by Ptitg** [comment]
That was my original intention. But logs are full of personal information (user account, phone number, IP address...). Impossible to share this as is.

**Comment by Viish** [comment]
Simply send it to me to sylvain.berfini@belledonne-communications.com

**Comment by Ptitg** [comment]
Logs sent in private.

**Comment by Viish** [comment]
Hi,

As you are using UDP transport protocol (the only one supported by OVH, I know...), the INVITE packets aren't being received by the server (or the answer isn't being received by the client) because the packets are too heavy and are being lost.

I recommend you disable ICE that causes a huge increase in the packets size and see if it's better.
There is no change between the previous version and the current one that would explain such issue, except maybe for a few bytes increase of the INVITE body size.

Cheers,

**Comment by Ptitg** [comment]
Hi,

Thank you for your feedback.
With or without ICE it's the same.

Cheers,

**Comment by Viish** [comment]
Hi,

I just tried to login my SIP OVH account on 5.0.5 android release and everything is fine.
I didn't touched any of the setting, simply connected my account on a fresh install.
What changes did you made to the settings?

Cheers,

**Comment by Ptitg** [comment]
Hi,

I don't remember changing the settings recently (or maybe by mistake). But I just did some tests. And it works by changing SRTP to ZRTP in options > calls > media encryption (in french : options > appels > chiffrement du média).

Cheers,

**Comment by Viish** [comment]
Hi,

Indeed SRTP adds more bytes in the INVITE than ZRTP.
For information the default media encryption is set to None, which adds even less bytes ;-)

Cheers,
