### ISSUE TITLE
Facing ECHO issue while "on speaker" during the call

### ISSUE THREAD

**Issue by mahesh-manseta** [BelledonneCommunications/linphone-android#1857]
Hello Team,

I am continuously facing echo issue when speaker is ON during the call in some of the high-end devices like OnePlus 10 Pro

When i make call whether it's outgoing or incoming and turn ON the SPEAKER, there is a continuous echo voice issue in my OnePlus 10 Pro device.

 - Device: [OnePlus 10 Pro]
 - OS: [Android 13]
 - Version of the SDK [5.2.20]
 - App version: local build [5.1.0]
 - Oxygen OS.

**SDK logs**

[attached logs](https://drive.google.com/file/d/1miKh1HAmAyDWfCMDSF4c2L1Y1iZQe5im/view?usp=sharing)

Thank you, looking forward to the response!

**Comment by Viish** [comment]
Hi,

Your device declares it has a built-in echo canceller, so we uses it.

You can try to use OpenSLES audio driver instead of AAudio to see if it improves things.
If it does, it means on this device, AAudio can't use hardware echo canceller.
If it doesn't, it means the device lies about it's hardware echo canceller, or it is misbehaving.

In any way, you can try to disable the user of the hardware echo canceller to use a software one instead.
For that, please follow this wiki section: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Audio%20devices/#HHardwareechocancellernotworking

Cheers,
