### ISSUE TITLE
Can only connect to Sipgate on phone reboot

### ISSUE THREAD

**Issue by edent** [BelledonneCommunications/linphone-android#1889]
Hello! Love the software. It's a great way to use SIP since Android disabled it in the native dialler

1. **Describe the bug**
I can connect to Sipgate.co.uk using UDP. I am able to make and receive calls. But if I quit the app and restart it, the account sticks at "connection in progress" for a while and then fails.

If I reboot my phone, the connection works again!

3. **To Reproduce** (mandatory)

Add a Sipgate.co.uk account. Place a call. Forcekill or restart the app. Reopen app. Account connection fails.

Reboot the phone and the account connects correctly.

4. **Expected behavior** (mandatory)

When I restart the app, the Sipgate connection should reconnect.

5. **Please complete the following information** (mandatory)

 - Device: OnePlus 5T
 - OS: Android 13 (Lineage 20)
 - Version of the App 5.06
 - Version of the SDK 5.2.23
 - Where you did got it from F-Droid
 - Please tell us if your Android is a Lineage OS or another variant. Lineage 20

6. **SDK logs** (mandatory)

The logs contain phone numbers that I've dialled. Happy to share privately, but not in public.

7. **Adb logcat logs** (mandatory if native crash)
N/A

8. **Screenshots** (optionnal)

N/A

9. **Additional context** (optionnal)

**Comment by Viish** [comment]
Hi,

To understand what's going wrong after the reboot, I'll need the logs.
You can send them to me at linphone-android@belledonne-communications.com, and don't forget to add a link to this issue.

Cheers,

**Comment by Viish** [comment]
Thanks for the logs.

Your problem is that UDP packets for REGISTER aren't being received (or the answer is being lost), so you keep sending REGISTER over and over etc...
As your log doesn't include the case where it works I don't know why the first time the app starts after a reboot it does work.

I see that you are using a sip.linphone.account at the same time, and that will cause the REGISTER to be a bit longer because of the org.linphone.specs params added to the Contact header.

We are working on a specific mode of settings for users in UDP to reduce the packets size to the lowest possible to prevent that, but it's not ready yet...
