### ISSUE TITLE
Problem with conference call

### ISSUE THREAD

**Issue by ThoracicStorm** [BelledonneCommunications/linphone-android#1935]
Trying to start a conference call by adding calls using the addParticipant function, but the receivers don't seem to be a part of the conference and cancelling the call on sender disconnects all the calls

**Comment by Viish** [comment]
That's a "local" conference. In that mode, the device that creates the "conference" merges all stream locally, so everyone can hear each other, but no-one knows there are in a conference since there is no information sent by SIP about that.
If you want a real conference, you have either to start a group call or schedule it, but for that you need a conference server.

**Comment by ThoracicStorm** [comment]
Would I be able to join this conference from another device?

If so how do I go about it?

**Comment by Viish** [comment]
Depends on the conference you are talking about:

- If it's a remote conference you'll have a SIP uri to call that specific conference.
- If it's a local one you simply have to call the one hosting it and have it add you to it.
