### ISSUE TITLE
Does Linphone support multiple calls simultaneously?

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-android#1966]
Hello, I have a question.
I have 2 handsets on my Android device which is a dispatching desk. 
And Linphone supports multiple sip accounts, for example, 1001 and 1002. 
I need one handset to use the account 1001 and during the process of answering a call, I want the other handset to use 1002 to make or answer calls.

I need to have two separate calls happening simultaneously on two handsets. 
Does Linphone support this?

Thank you in advance for reviewing my question.

**Comment by Viish** [comment]
Hi,

We don't support more than one active call at the same time unless they are merged together, so the answer is no, sorry

**Comment by happyfsyy** [comment]
Hello, @Viish may I ask if it will be possible to support this in the future? 
I just want to have the ability to make simultaneous calls with multiple SIP accounts.
If it's not possible, why would there be a need to create multiple accounts?

**Comment by Viish** [comment]
It might, the hard part is handling the audio while multiple calls are active at the same time.
However that's not on our short/mid term roadmap because the use-case of multiple active calls at the same time is quite a niche, unless it's a group call or a meeting. 
That being said, feel free to contact our sales department if that is something you really need and that your are disposed to fund it.
