### ISSUE TITLE
using config to refresh registration on launch

### ISSUE THREAD

**Issue by brianomchugh** [BelledonneCommunications/linphone-android#2027]
With the iOS SDK, my registration is saved and refreshed automatically (on app launch) when I set the config file like this:
```
// IMPORTANT : In this tutorial, we require the use of a core configuration file.
// This way, once the registration is done, and until it is cleared, it will return to the LoggedIn state on launch.
// This allows us to have a functional call when the app was closed and is started by a VOIP push notification (incoming call
// We also need to enable "Push Notitifications" and "Background Mode - Voice Over IP"

let configDir = factory.getConfigDir(context: nil)
try? mCore = factory.createCore(configPath: "\(configDir)MyConfig", factoryConfigPath: "", systemContext: nil)
```
I am having trouble getting the same behavior on the Android version. Is it possible or do I just have to login/register each time? This is what I am trying but nothing happens:
```
factory.setDebugMode(true, "Hello Linphone")
core = factory.createCore(context.filesDir.absolutePath + "/.linphonerc", context.filesDir.absolutePath + "/linphonerc", context)
```
And I do see in the logs:
```
Reading config information from /data/user/0/com.test.app/files/linphonerc
Initializing LinphoneCore 5.1.73
```

**Comment by Viish** [comment]
Hi,

This is the right way, so it should work. It is exactly what we do in our own app.
Check that you don't call `core.clearAccounts()`, `core.clearProxyConfig()` or `core.clearAllAuthInfo​()` by mistake somewhere in your app, or that you don't remove it or overwrite it at some point.

If issue persists, please attach full logs.
Also note that you should use 5.2.X release of our SDK instead of 5.1.73.

**Comment by brianomchugh** [comment]
Thank you for the sanity check and the tip about updating the SDK. I was not setting up the coreListener correctly.
