### ISSUE TITLE
Why does my application sometimes force close when it is at the "Call.State.StreamsRunning" stage?

### ISSUE THREAD

**Issue by fazilmuammar** [BelledonneCommunications/linphone-android#2044]
I'm using Lib Linphone version 5.1.0

the Problem is sometimes my app force close when it is at the "Call.State.StreamsRunning" stage,   but the error log does not appear.

so i don't know how to fixing it

can anyone help me please?

thank you

**Comment by Viish** [comment]
Hi @fazilmuammar,

Please provide debug logs from app & SDK stack trace for the crash, otherwise I can't help.

Cheers,

**Comment by Viish** [comment]
Hi @fazilmuammar,

The log file doesn't contains the stack trace of the crash so it doesn't help much.
Please note your aren't using the latest release (currently 5.2.112 but 5.3.0 will be released soon), maybe your issue is already fixed, so I strongly recommend you to update.

Also know that we only support the latest release.

Cheers,

**Comment by fazilmuammar** [comment]
Hi @Viish 

Okay @Viish  but where i can download Linphone Sdk 52.112 (aar) for Android Native?

**Comment by Viish** [comment]
@fazilmuammar on our maven repository : https://download.linphone.org/maven_repository/org/linphone/linphone-sdk-android/?C=M;O=D

**Comment by fazilmuammar** [comment]
Okay @Viish Thank you for ur help.

cheers
