### ISSUE TITLE
Changing name for packaging the apk

### ISSUE THREAD

**Issue by rakesh91** [BelledonneCommunications/linphone-android#2060]
Hi,
I was able to build (latest version) the app in Android studio but to change the name of the package in apk the method specified in the documention is not working. 
As in, there is no method named getPackageName() in app/build.gradle. However, there is a holder packageName upon changing it the build is failing with error
"No matching client found for package name 'org.givenPackageName.debug".

Thanks in advance.

**Comment by Viish** [comment]
HI @rakesh91,

The `No matching client found for package name` is a Google Services error because the package name you set doesn't match any in the app/google-service.json.
Check you either replaced it by yours or that you have removed it before building the app, as Android Studio does a strong check to make sure the configuration is OK.

Thanks for the documentation feedback anyway, I'll update the README accordingly.

Cheers,

**Comment by chillcollex** [comment]
Hi @Viish,
sorry to bother you again, I followed the docs and changed the packageName value, and got this error, is the docs outdated? 

Activity class {org.linphone/org.linphone.ui.main.MainActivity} does not exist
