### ISSUE TITLE
SIP/2.0 401 Unauthorized when Registering Sip Account

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#2094]
Hi @Viish, 

hope you doing great, i am trying to register on linphone even the play store app and the from latest source aswel but i am getting this SIP/2.0 401 Unauthorized and unable to register . On other clients i.e zoiper account works well and gets authenticated successfully .

Please suggest what is missing to get successful registration. Thanks

here are the logs from Android Studio LogCat. Please check the attached file.
[logs_linphone_1.pdf](https://github.com/BelledonneCommunications/linphone-android/files/14169936/logs_linphone_1.pdf)

**Comment by Viish** [comment]
Hi @Adnan-addi,

Given your logs, the issue seems to be the qop value in the WWW-Authenticate that we do not seem to support:
```
23:16:06.189 I channel [0x75d019d280]: received [484] new bytes from [UDP://
sip.kurira.com:5060]:
23:16:06.189 I SIP/2.0 401 Unauthorized
23:16:06.189 I Via: SIP/2.0/UDP
10.52.21.138:40665;received=223.123.43.14;branch=z9hG4bK.pgCCE~8Fh;rport=2
122
23:16:06.189 I To: sip:
+447824869580@sip.kurira.com;tag=9f79.cd41df51d552ae3e8473077f7e5b4299
23:16:06.189 I From: <sip:+447824869580@sip.kurira.com>;tag=JRH3VP5Ix
23:16:06.189 I Call-ID: zH4KO1JOby
23:16:06.189 I CSeq: 37 REGISTER
23:16:06.189 I WWW-Authenticate: Digest realm="sip.kurira.com",
nonce="qOBJ6D5Gzh9scvtgPjr+yUlWx+OXkaLzPDgcT0xFvmAA", qop="auth-
int,auth"
23:16:06.189 I Server: OpenSIPS (3.4.3 (x86_64/linux))
23:16:06.189 I Content-Length: 0
23:16:06.189 I
23:16:06.189 I
23:16:06.191 I channel [0x75d019d280] [484] bytes parsed
23:16:06.191 I Found transaction matching response.
23:16:06.191 I Changing [client] [REGISTER] transaction [0x75d0129540], from
state [TRYING] to [COMPLETED]
23:16:06.191 I linphone_core_find_auth_info(): returning auth info
username=+447824869580, realm=sip.kurira.com
23:16:06.191 I AuthStack::authFound() for
Username[+447824869580];Userid[];Realm[sip.kurira.com];Domain[sip.kurira.com];A
lgorithm[];AvailableAlgorithms[];
23:16:06.191 I Auth info found for [+447824869580] realm [sip.kurira.com]
23:16:06.191 E belle_sip_fill_authorization_header, unsupported qop [auth-int], use
auth or nothing instead
```

Given the error message, I'd say you have to change your OpenSIPS server configuration to change the qop value from `auth-int` to `auth`.

That being said, please keep in mind that Linphone source code is distributed under GPLv3 license that requires you to mention the original license and publish your own app source code under the same license, which doesn't seems to be the case for the app currently on the Play Store and AppStore.
So either update your app & website to properly follow the license or contact our sales department using the contact form on our website (https://linphone.org/contact) to purchase a proprietary license.

Cheers,

**Comment by Adnan-addi** [comment]
@Viish 

Hi , Hope your doing well.

After reviewing the details we came to this point that we cannot change server qop settings. Is there a way to change it at sdk level and make it work ?

**Comment by Viish** [comment]
Hi @Adnan-addi, 

Not with our public APIs, no. You'd have to hack our SDK source code to make the change.

You can also contact our sales department for a quotation for us to do the work though.

**Comment by Adnan-addi** [comment]
any link or contact of the sales department? i can't find it please help. Thanks

**Comment by Viish** [comment]
@Adnan-addi Simply use contact form button on our website https://linphone.org/contact#content-bottom3
