### ISSUE TITLE
Stay running without persistent notification

### ISSUE THREAD

**Issue by corobin** [BelledonneCommunications/linphone-android#2111]
1. **Describe the bug** (mandatory)

In order to make Linphone continue running in background, it always shows a persistent notification.

Usually in other apps, I can still dismiss that notification without affecting functionality by turning off that notification in the Android app notification settings.

However, if i do that with Linphone the app does not stay in background anymore.

So currently the only way for Linphone to stay open in background is to have the persistent notification.

3. **To Reproduce** (mandatory)

1. Open Linphone settings > Advanced
2. Toggle to turn ON "Background mode"
3. At this time, the Linphone persistent notification should pop up
4. Exit Linphone app
5. The persistent notification should still be there
6. test - incoming calls work fine
7. Long hold on the persistent notification, then click gear icon at top right (alternatively, go to Android Linphone notification settings)
8. Toggle OFF "Linphone service notification"
9. wait a brief moment or restart phone
10. Actual behaviour: Linphone no longer runs in background
11. test - incoming calls no longer show up

12. **Expected behavior** (mandatory)

Linphone remain running in background

13. **Please complete the following information** (mandatory)

 - Device: Pixel 7
 - OS: Android 14
 - Version of the App 5.2.3
 - Version of the SDK 5.3.14
 - Where you did got it from Play Store
 - Please tell us if your Android is a Lineage OS or another variant. default Pixel OS

14. **SDK logs** (mandatory)

Feature request, not a bug in call functionality.

15. **Adb logcat logs** (mandatory if native crash)

Not crash.

16. **Screenshots** (optionnal)

N/A

17. **Additional context** (optionnal)

While searching, I found #545 which describes an option "Enable service notification" that I do not see in the current version of Linphone. It sounds like it used to be possible to keep Linphone running in background without a persistent notification, but that was removed.

This is a request to support being able to keep Linphone running without a persistent notification.

**Comment by Viish** [comment]
Hi @corobin,

No it is not possible (at least since a few years) to have an app always running in the background without having a visible notification.

Note that this mode (previously called "service notification") always was a workaround. The real and proper solution is to rely on push notifications to wake up the app when necessary.

Cheers,

**Comment by corobin** [comment]
Hi @Viish , thank you for the quick reply.

Would you mind elaborating on the "push notification" part?

I don't see a push notification option in "Network" settings but I do see an "Allow push notification" option in the settings for each SIP account. However, despite enabling it, incoming call does not come through unless Linphone is running (in fore or background).

The VOIP service says that the softphone must be registered to get incoming calls, and it only shows as registered when Linphone is running.

Is this a compatibility issue with the service provider?

The other issue, as you have seen my comment in #1395, is that calls drop if I enable push notification.

**Comment by Viish** [comment]
@corobin sadly a push certificate is bound to both an app and a server, that's why push are only supported for our own SIP service, and the same happens for all other VoIP apps.

We are working on a "push gateway" mode where our own SIP proxy would trigger a push notification when notified of a call or message from a third party linked SIP account, but that's not ready yet...

If you host your own server it's easy to fork our app and change the push certificate to use yours though. If not, you have to rely on the background mode with the full time notification. Note that with recent Android versions there is an OS setting to hide permanent notifications such as ours from the status bar (it's only visible when you pull it down).

**Comment by corobin** [comment]
that explains it, thank you!
