### ISSUE TITLE
Push Notification stack confusion

### ISSUE THREAD

**Issue by ParticleCore** [BelledonneCommunications/linphone-android#2127]
Currently building a SIP softphone using the linphone SDK on Android that is meant to be deployed to various customers, not necessarily related to each other.

Each customer has their own SIP service in place, and the one being developed will be used with that service similar to a plug-and-play implementation where the app only requires the bare minimum data (username, password, domain/ip) in order to connect, similar to a physical SIP phone. We have no control over which server the customers have.

All looks good so far, but I am stumbling on the Push Notification part and I cannot get a clear read of this in the available documentation, so I hope it would be possible to clarify some things for me.

1. There are 2 modes the linphone SDK can work with push notifications; automatically (it handles everything) or manually (the app does its own thing)

   - Automatic means the customer's server sends the push on its own, and the SDK will receive it, and handle it on its own too.
   - Manual means the customer's server sends the push on its own, and the app handles everything (SDK does nothing).

Is the above analysis correct?

2. Regarding the server sending the push; this is something the server the customer has requires the capability to send PUSH on its own. This is not something we can overcome on our own without implementing another server (like Flexisip) alongside the customer's to handle sending the PUSH. The server on the customer's site needs to support sending push notifications to the registered devices. If it does not support that, then any calls will only be received while the app is connected (not closed or in the background).

Is the above analysis correct?

**Comment by Viish** [comment]
Hi @ParticleCore,

If our SDK detects a push configuration setup for the app (and if push notifications have been enabled), it will automatically add push parameters to the Contact header of the REGISTER.
If you want, you can disable that behavior but you'll need to do yourself the process of gathering the device token and sending it to the server.

Once a push is being received by your app, if you have configured our FirebaseMessaging Service in your Manifest, it will either process it if the Core is available, otherwise it will send your app a broadcast intent with action `org.linphone.core.action.PUSH_RECEIVED` and it's up to you to catch it in a BroadcastReceiver and start the Core.
If you didn't declared our FirebaseMessagingService, you'll have to do all the job.

Our SDK handling push is merely a simplification tool for app developpers to not worry about that part, but everything can be disabled to let you have full control.
See https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/ for more info.

That being said, regarding your setup, it will be tricky as you want to support many servers that are out of your control, so the server push configuration will likely never be the same, and you won't be able to support all of them in your app.
This could be workarounded using a Flexisip server as a push gateway. For more information, see https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/
