### ISSUE TITLE
change speakers and microphones

### ISSUE THREAD

**Issue by gaoruiqing187** [BelledonneCommunications/linphone-android#2166]
Hi, I'm having some trouble switching between speakers and microphones. Below is my code, can be used before, suddenly found yesterday whether core. GetExtendedAudioDevices or core. GetAudioDevices can only be called a Unknown device. I also wrote the permission in the Manifest, please help solve it，thank you！
<img width="1189" alt="image" src="https://github.com/BelledonneCommunications/linphone-android/assets/14845602/225091fd-c770-4aa2-9b57-f3e9dfbada4d">

**Comment by Viish** [comment]
HI @gaoruiqing187,

Your way of checking capabilities is wrong.
Use `device.hasCapability(AudioDevice.Capabilities.CapabilityPlay)` instead of `device.getCapabilities() == AudioDevice.Capabilities.CapabilityPlay)`
For example : https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/utils/AudioRouteUtils.kt#L283

Cheers,

**Comment by gaoruiqing187** [comment]
That's not my problem. My problem is that I don't have access to other inbound and outbound devices
