### ISSUE TITLE
Linphone 5.2.5 Android feature request: initiate early media audio/video call and preview button

### ISSUE THREAD

**Issue by jsk747** [BelledonneCommunications/linphone-android#2198]
Hello Team,

The Linphone "Call settings" include "accept early media"  and "ring during incoming early media".
I miss a feature to initiate a new call including an early media request (outbound).  

This is perhaps not so much a bug, but rather a feature request.  Maybe this also requires an UI 
addition with an additional button:   Preview/Prelisten to incoming early media call.

Without the capability above it is not possible to test "accept early media" with two linphone devices.
As a bonus:  as both the initiating and the receiving side may request early media; Maybe another
button could be added to request early media to the call originator for incoming calls. 

Tx,

**Comment by Viish** [comment]
Hi @jsk747,

You don't need such feature as the caller doesn't decide if recipient will send early media or not, only the recipient devices decides, that's why there is only one setting "accept early media" (name is misleading).
If you toggle it on and then call it, it will answer 183 early-media instead of 180 ringing.

Cheers,
