### ISSUE TITLE
linphone 6 - two missing settings

### ISSUE THREAD

**Issue by corobin** [BelledonneCommunications/linphone-android#2252]
Hey there, I couldn't find a place for beta feedback, hopefully this is acceptable.

I noticed two options that were present in v5 that are no longer in v6, but they could still be useful.

1. port selection - some services may have non-standard ports (e.g. voip.ms uses different ports for tls), so it is useful to still be able to configure a port

2. disable logging - this is perhaps not super important, but when not logging for a bug report it doesn't hurt to be able to disable logging like in v5. the toggle for that can be in the same place as the clear/upload logs buttons

**Please complete the following information** (mandatory)

 - Version of the App/SDK: see screenshot
 - Where you did got it from: Play Store
 - Please tell us if your Android is a Lineage OS or another variant: no

**Screenshots** (optionnal)

![Screenshot_20240926-210101](https://github.com/user-attachments/assets/577bdabb-92b2-47c0-a659-3348d94fe290)

Thanks!

**Comment by Viish** [comment]
Hi @corobin,

You can configure the proxy port in the proxy URL setting like this: "sip:voip.ms:5062;transport=tls" like it was possible in 5.2 version.

Regarding the logging, it's a change we want because we lost a lot of time before explaining how to enable logs, and then people had to reproduce it in order for us to get valuable information. Now that logging is always enabled, this gets a lot more easier. It doesn't cost much as there is a log rotate in our SDK preventing log files to go higher than 10Mo.

Cheers,
