### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by syjml** [BelledonneCommunications/linphone-android#241]
[ 16%] Performing configure step for 'EP_bctoolbox'
loading initial cache file /Users/jml/gitCode/linphone-android/WORK/android-armv7//tmp/EP_bctoolbox/EP_bctoolbox-cache-RelWithDebInfo.cmake
-- Using mbedTLS
-- Could NOT find Decaf (missing: DECAF_INCLUDE_DIRS DECAF_LIBRARY) 
-- DTLS SRTP not available
-- Package file name is bctoolbox-0.6.0-82
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jml/gitCode/linphone-android/submodules/bctoolbox
[ 16%] Forcing build for 'EP_bctoolbox'
[ 17%] Performing build step for 'EP_bctoolbox'
make[4]: *** No targets specified and no makefile found.  Stop.
make[3]: *** [/Users/jml/gitCode/linphone-android/WORK/android-armv7/Stamp/EP_bctoolbox/EP_bctoolbox-build] Error 2
make[2]: *** [CMakeFiles/EP_bctoolbox.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by bestMechanic** [comment]
re clone bctoolbox submodule.

**Comment by mzimmers** [comment]
Hi - 

I'm encountering the same error. Can someone please tell me what the fix was? Here is some of the error message:
`-- Could NOT find Decaf (missing: Decaf_DIR)
-- DTLS SRTP not available
CMake Error at CMakeLists.txt:121 (find_package):
  Could not find a package configuration file provided by "BcUnit" with any
  of the following names:

    BcUnitConfig.cmake
    bcunit-config.cmake`
Thank you.
