### ISSUE TITLE
[Feature request] Option to accept early media (video before answering)

### ISSUE THREAD

**Issue by kietas** [BelledonneCommunications/linphone-android#29]
I see that linphone core already supports early media. It would be very usefull to be able to see who's calling in some use cases (video intercom, etc).

**Comment by kietas** [comment]
I tried to build linphone-android with early media enabled and it kind of works. I see video but there is no way to answer and it's only possible to hang up. Are there any plans to implement this feature?

**Comment by DatBewar** [comment]
Hello, it's not in our TODO list for the moment but it's could be add in the future maybe.

**Comment by salmonellad** [comment]
Where can i read more about video early mesia

**Comment by salmonellad** [comment]
*media

**Comment by kietas** [comment]
I could not find proper documentation myself. It's easy to enable it on linphone core but android app does not allow you to answer an incoming call with early media enabled.

**Comment by alexiagonzalez** [comment]
Good morning, and thanks a lot for all your good work.

I don't know if I'm acting properly asking this after the issue was closed, but I'm quite interested on the ability of answering a call after an early media is displayed the the user. (I'm developing an app to see a video intercom signal).

For now, I only can display a video preview (early media) without answering the call, but I'm still looking for a way to answer it after that. 
Any news since this issue was closed? or any way to get this goal once the early media is shown? 
Any plans to implement this feature finally?

Thanks in advance.

Best regards.

**Comment by Viish** [comment]
@alexiagonzalez It's easy, simply accept the call while it is in early media state.

**Comment by alexiagonzalez** [comment]
Hi Viish, thanks for your quick answer.

That's what I tried, as the documentation says, but with no result... I accept early media this way: 

LinphoneManager.getLc().acceptEarlyMediaWithParams(mCall, mCall.getRemoteParams());

and later in other class, (when user press a button to accept), I try to accept the call this way:

LinphoneManager.getLc().acceptCallWithParams(mCall, params);

but video intercom continues with calling sound, and there's no signal of call acceptance. Call acceptance works perfectly without accept early media previously. Are you totally sure that of early media + call acceptance works nowadays? Do you have any sample code that works for sure?

Thanks a lot Viish.

**Comment by Viish** [comment]
Hi,
You don't have to acceptEarlyMediaWithParams.
Simply call call.accept() or call.acceptWithParams() when you want to.
You can test with linphone-android (master branch), it supports receiving early media.
If you look at the source code, the process of answering such a call is the same as for a call without early-media.
Cheers,

**Comment by alexiagonzalez** [comment]
Hi again Viish, 

The problem was mine. First of all, I have to use an old version of Linphone as base for my project.  Nowadays, it's not easy for me to merge my project with latest Linphone project, so I implemented my own simplified version of video preview.

I had a problem with the call params before accepting that I've just resolved, so everything works ok now, and this issue could be closed again.

Thanks for all again, and thanks for your support.

Best regards.

**Comment by Viish** [comment]
You're welcome :)

**Comment by Steven1937** [comment]
Hi, could u please tell me how to  achieve video before answering?  On Call comming side , I replaced the "linphonecore.acceptCallWithParams" with "LinphoneCore.acceptEarlyMedia() ", but no video display,  Is there something I need to do for Call outgoing side ?  I confused how to send video data when call SipCoreManager.getInstance().newOutgoingCall()? , or how to send video data before connected?   Thanks in advance.

**Comment by Steven1937** [comment]
Hi, could u please tell me how to  achieve video before answering?  On Call coming side , I replaced the "linphonecore.acceptCallWithParams" with "LinphoneCore.acceptEarlyMedia() ", but no video display,  Is there something I need to do for Call outgoing side ?  I confused how to send video data when call SipCoreManager.getInstance().newOutgoingCall()? , or how to send video data before connected?   Thanks in advance.
