### ISSUE TITLE
Dialing Is Too Slow

### ISSUE THREAD

**Issue by muellert** [BelledonneCommunications/linphone-android#355]
Hi!

I have Linphone 3.3.2 and frequently experience the following problem:

I want to dial a number to make a phone call.

I always have to take extra care to dial very slowly, with almost a second's pause between digits, in order to have all digits appear on the screen, and in the correct order. If I type the number in my normal speed, I usually miss about 2/3 or more of them, thus not being able to reach the correct target. On the same phone, the normal phone application does not have this problem at all, and, actually, other areas of Linphone are much faster. It's just this part which is really, really slow. It would be great if you could fix this problem.

Thanks!

**Comment by xekon** [comment]
I have the same problem, I am surprised this issue was closed instead of asking more questions.
My phone is an LG G7 ThinQ and I am having the same issue.

I am fairly tech savvy, the phone is very clean, meaning no bloat apps installed.
The built in app dials quickly, as does csipsimple.
I used csipsimple for years and even though its no longer under development it still works to this day.

I was interested in using linphone to try out video calling.

This is not a minor glitch, its fairly bad and with normal dialing speed is easily reproduced every time, just as @muellert said you have to dial very slow and very carefully or you will miss some of the digits. My friend has an even newer phone than mine, I plan to see if his also does the same thing.

I will make a video of just how bad it is and attach it here later.

**Comment by Viish** [comment]
Problem is (at least currently) that if the system policy is to play DTMF tones, we try to do it.
However our sound card takes a bit toom much of time to initialize and it freezes the UI shortly.
I've removed the DTMF sounds on the dialer for the next release (4.6.0), dialer will be as smooth as the rest of the UI now.

**Comment by xekon** [comment]
Awesome, looking forward to trying it! Thanks!

**Comment by Viish** [comment]
> This won't affect in call use of buttons will it?

No it won't ;-)
