### ISSUE TITLE
I need hardware encodec

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#423]
Hi,

Now I use linphone4.0.1, is it software encodec by default?
 I need hardare encodec. please tell how to modify to  enable hardware encodec? 
and after I enable hardware encodec, how to verify it is hardare encodec. 
my box is android6.0. 

thanks.

**Comment by Viish** [comment]
If your box is running Android 6, it will use hardware encoder by default if available.
To check, take a look at the name of the encoder/decoder filter in the library logs: if the name is MediaCodec then you are using hardware filter, otherwise it will use software implementation.
Note that only H264/H265 is using hardware feature, other codecs (VP8 and all audio ones) are software.

**Comment by fengsimon** [comment]
thanks !
You mean when my two devices are talking on video, are they using hardware encoder now? 
How to confirm? Because I don't think the video effect is good now.
In addition, do I need to turn off vp8, and does it affect hardware encodec?

thank you very much.

**Comment by fengsimon** [comment]
thanks !
You mean when my two devices are talking on video, are they using hardware encoder now?
How to confirm? Because I don't think the video effect is good now.
In addition, do I need to turn off vp8, and does it affect hardware encodec?

Another question, if my question is closed, but I continue to  want ask  question based on the title, and then write it down below, can you see it?  if you can't see it, do I need to create a new issue?
thank you very much.
@

**Comment by Viish** [comment]
If you want to be sure you are using hardware video encoder, then yes you should disable VP8.
Please keep in mind this is to report us issues such as crashes or app bad behaviors etc..., not to get help. For that you have our mailing list.
