### ISSUE TITLE
API changed? Many core classes mising on version >= 4

### ISSUE THREAD

**Issue by vaiden** [BelledonneCommunications/linphone-android#484]
I'm migrating my project from 3.4.1 to 4.1 due to this: https://github.com/BelledonneCommunications/linphone-android/issues/378#issuecomment-465604088

When trying to build most of the core classes and interfaces are missing. Partial list:
import org.linphone.core.LinphoneAddress;
import org.linphone.core.LinphoneAuthInfo;
import org.linphone.core.LinphoneCall;
import org.linphone.core.LinphoneCallStats;
import org.linphone.core.LinphoneChatMessage;
import org.linphone.core.LinphoneChatRoom;
import org.linphone.core.LinphoneContent;
import org.linphone.core.LinphoneCore;
import org.linphone.core.LinphoneCoreException;
import org.linphone.core.LinphoneCoreFactory;
import org.linphone.core.LinphoneCoreListener;
import org.linphone.core.LinphoneEvent;
import org.linphone.core.LinphoneFriend;
import org.linphone.core.LinphoneFriendList;
import org.linphone.core.LinphoneInfoMessage;
import org.linphone.core.LinphoneProxyConfig;

What happened? Was there an API change?

**Comment by Viish** [comment]
Hi,
Yes with 4.0 release we introduced a new Java wrapper that is automatically generated from our C/C++ library instead of having to manually wrap every new function.
However if you want to update the liblinphone without using the new wrapper you can disable it using ./prepare.py -DENABLE_JAVA_WRAPPER=NO which will build the previous one.
Keep in mind the previous wrapper is highly deprecated, we aren't adding new features in it and it isn't officially supported anymore.

**Comment by vaiden** [comment]
The 4.1 version is built using cMake, not prepare.py.
Is it the same switch?

**Comment by Viish** [comment]
Yes it is

**Comment by vaiden** [comment]
> Yes it is

This fails because of code built without the wrapper: https://github.com/BelledonneCommunications/linphone-android/issues/486
