### ISSUE TITLE
"Registration failed" on Huawei Honor 5X (Kiwi), Linphone 4.0.1 (F-Droid), LineageOS 15.1 (Android 8.1)

### ISSUE THREAD

**Issue by dvzrv** [BelledonneCommunications/linphone-android#487]
Hi! I'm having trouble (weirdly enough sometimes, but then persistent), to get the registration working to my SIP gateway.
This used to work just a day ago, but now doesn't.

Attached you can find an excerpt of the debug log for Linphone (domain and registration info are redacted), where the intermittent

```
E libc    : Access denied finding property "net.dns1"
E libc    : Access denied finding property "net.dns2"
E libc    : Access denied finding property "net.dns3"
```

suggests problems in using DNS services on the device.
This is really bizarre, as just yesterday I could register fine and make a call.

[kiwi-linphone.txt](https://github.com/BelledonneCommunications/linphone-android/files/2896712/kiwi-linphone.txt)

**Comment by Viish** [comment]
Can you try with the latest SDK available please? We added some logs that will help us get a better understanding of your issue.
The access denied for dns property isn't a real error, it is expected on all Android > 8. We have a new mechanism for getting the DNS server but in your case doesn't seem to work.

**Comment by dvzrv** [comment]
@Viish why did you close this? It's still a problem.

If people don't instantly reply to a bug report they invested time into reporting to you for free, show some respect and wait for them to actually get back to you.
I have plenty of other projects I'm working on and don't have the constant time to debug or rebuild a bunch of stuff all over the place (especially not instantly).

That being said: I provided you with the information on how this application was installed/retrieved and need to first investigate how exactly it was built and what the SDK version was. I'm not really up for building the app myself, if I don't have to.

**Comment by Viish** [comment]
Indeed I did close this issue because it was "inactive". It is my way of cleaning all the issues that are opened here and then abandoned, because I know that if the person that submitted it is still around it can reopen it.

Anyway this problem is related to your device and most probably on the Lineage OS ROM you have. We have a lot of devices on which we test and we never had this issue before (including in our own Huawei devices, even if not this one exactly).

That being said, if provided with all the relevant information we'll do what we can to fix that, but our main focus is to have an app that works on most of the devices (on their factory ROM), which is already a never ending job.

**Comment by Viish** [comment]
Reopen this issue once you'll have logs, in the meantime I close it.
