### ISSUE TITLE
early media function

### ISSUE THREAD

**Issue by fengsimon** [BelledonneCommunications/linphone-android#555]
Hi,
I know that two linphone-based boxes can implement early Meida through some states and interfaces of early meida, but one is based on linphone box, and the other is based on pure SIP box. How can we implement early Meida function?
I think one way is that when the caller based on linphone exhales, the callee based on SIP connects directly, but at this time I let the bell continue ringing and set the MIC of the callee to 0. At this time, you can only see the video of the caller, and only the caller's voice, similar to early meida, but there is a problem. When either side press the answering key on the main interface, how can the other side know? ?
Do you have any good suggestions?
 Whether the caller based on linphone can send video and voice directly when he exhales，If so, what is the interface?
thanks.

**Comment by Viish** [comment]
In liblinphone, to enable incoming early media, set incoming_calls_early_media in [sip] section of the linphonerc_factory to 1.
It will send the 183 to the caller, play audio instead of ringing and even display video if there is a stream on the call incoming activity.
If the user accepts the call, it will send the 200 OK and go to the CallActivity like a regular call.
