### ISSUE TITLE
Only one sip address is shown

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#576]
![image](https://user-images.githubusercontent.com/14617699/56254441-7ccccb80-60c9-11e9-80be-697af3b1ace2.png) ![image](https://user-images.githubusercontent.com/14617699/56254442-7f2f2580-60c9-11e9-8ab7-41e2a2627545.png)

And only localpart is shown:
![image](https://user-images.githubusercontent.com/14617699/56254443-80f8e900-60c9-11e9-86fc-4d159ca93b14.png)

**Comment by Viish** [comment]
It could be interesting indeed to see why only one of the two is displayed.
Can you add a log for the data1 variable in syncValuesFromAndroidCusor method from LinphoneContact class ?

**Comment by 532910** [comment]
Really, some time later, it has beed updated and now it shows two records, but still without domain.

**Comment by Viish** [comment]
Yes the app hides the domain part if it matches the domain of the default proxy config or the "default_domain" string in res/values/non_localizable_custom.xml.

**Comment by 532910** [comment]
OK, it may hide on the display screen, but must show on the edit.

**Comment by Viish** [comment]
Our point is that if the domain matches the default one, there is no need to show it on edition mode because the change will probably only affect the username.
If you still want to change the domain, you can add it during edition, the change will be applied.
Anyway, I just added a setting in non_localizable_custom.xml file so you can always show full SIP addresses.
