### ISSUE TITLE
linphone: sends a wrong "contact address" => registration fails

### ISSUE THREAD

**Issue by Thucnv** [BelledonneCommunications/linphone-android#59]
Hello all,
When i try to register with one account, it success
 ( flow  
  client: Register, 
  server: 401 unauthorized
  client: register with authorized
  server: 200 OK
)
contact field in message header: 
`Contact: <sip:2065@115.72.186.9:63422;transport=udp>;expires=1800`

But when i register with multi account, sometimes fail
 ( flow  
  client: Register, 
  server: 401 unauthorized
  client: register with authorized
  server: 200 OK
 client: register with authorized
  server: 200 OK
 .........
 client: register with authorized
  server: 403
)
contact field in message header when wrong: 
`Contact: <sip:105@192.168.1.10>;+sip.instance="<urn:uuid:c6b08969-b071-4e0f-9f82-d606dcdb8284>"`

I can see that linphone tries to register with a 
wrong "contact address": the IP in this contact address is the "local" 
IP of my laptop

Log linphone when register fail:
Client internal REGISTER transaction [0xe96d4d10] terminated
Refresher [0xe96d4d10]: contact address [192.168.1.10:5070] does not match channel address[(null):0] on channel [0xd68d0000]
belle_sip_refresher_start(): refresher [0xe96d4d10] is resubmitting request because contact sent was not correct in original request.
 
Please help me,
Thanks

**Comment by DatBewar** [comment]
Hello, this on Linphone Android or desktop?

**Comment by Thucnv** [comment]
Hello, It's Linphone Android.

**Comment by chuquangbao** [comment]
i have same problems. i restart my application with 2 connected sip accounts. I use Wireshark to trace the sent packages. But just only one account register normally,  2nd account is looped sending "Register" message ( over 20 messages)
I'm using bellsip 1.4.2 for iphone. 
Please, support to me!
Thanks.

**Comment by chuquangbao** [comment]
i add more log from Trace Log. 

2017-06-07 13:38:37.290 123CS[8273:803273] I/bel/channel [0x7fe0e0857400]: received [359] new bytes from [UDP://siptest01.123cs.vn:5060]:
SIP/2.0 200 OK
From: "105"<sip:105@vng3334.stgsip.123cs.vn>;tag=J8bfomizC
To: "105"<sip:105@vng3334.stgsip.123cs.vn>;tag=sc2vng1-186ca267fc43b309
Call-ID: cloBlOGNVV
CSeq: 22 REGISTER
Via: SIP/2.0/UDP 10.199.185.226:60693;rport=32830;received=203.205.57.126;branch=z9hG4bK.JQqKJQXXR
Contact: <sip:105@10.199.185.226:60693;transport=udp>;expires=1800

2017-06-07 13:38:37.292 123CS[8273:803273] I/bel/channel [0x7fe0e0857400] [359] bytes parsed
2017-06-07 13:38:37.293 123CS[8273:803273] I/bel/Found transaction matching response.
2017-06-07 13:38:37.293 123CS[8273:803273] I/bel/Changing [client] [REGISTER] transaction [0x60800014f990], from state [TRYING] to [COMPLETED]
2017-06-07 13:38:37.293 123CS[8273:803273] I/bel/Refresher [0x60000014f620]: contact address [10.199.185.226:60693] does not match channel address[(null):0] on channel [0x7fe0e00b4000]
2017-06-07 13:38:37.293 123CS[8273:803273] I/bel/belle_sip_refresher_start(): refresher [0x60000014f620] is resubmitting request because contact sent was not correct in original request.
2017-06-07 13:38:37.294 123CS[8273:803273] I/lib/linphone_core_find_auth_info(): returning auth info username=105, realm=vng3334.stgsip.123cs.vn
2017-06-07 13:38:37.294 123CS[8273:803273] I/bel/Auth info found for [test103_105] realm [vng3334.stgsip.123cs.vn]
2017-06-07 13:38:37.295 123CS[8273:803273] I/bel/Changing [client] [REGISTER] transaction [0x60800014ee90], from state [INIT] to [TRYING]

**Comment by jalpesh101291** [comment]
Please Visit my blog http://linphonecode.blogspot.in please at least one time visit i have ios and android source code

**Comment by locofungus** [comment]
I'm having a similar problem. I'm sitting in a hotel with a VPN connection routing all traffic. (openvpn)
The registration message is correctly coming from 192.168.5.129 (and being sent to siproxd) but the ip inside that request is the wifi address and not the VPN address, so siproxd is trying to send things to 192.168.1.65.

In other cases where there are multihomed hosts, it has been suggested to use the Firewall/NAT settings to set the correct address but that option appears to be missing for the android version.

**Comment by locofungus** [comment]
To update on the previous comment: I discovered ipv4 DNS queries were being attempted to various dns resolvers. I've now setup the firewall between the VPN and internet to redirect them all to the dns resolver that the VPN provides and registration is now working.

I have no idea who is making these DNS queries, nor why it fixes which ip is supplied for the contact address, but it might help someone else with the same problem.

**Comment by Thucnv** [comment]
[logregisterfail.txt](https://github.com/BelledonneCommunications/linphone-android/files/2187779/logregisterfail.txt)
i add log from LogCat.

**Comment by grit96** [comment]
@Thucnv did you ever figure out a solution to this problem?
