### ISSUE TITLE
phonebook selection on contact creation

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#590]
While editing existing contact works as expected, creation a new one creates it in the local linphone phonebook. Please add support to choose phonebook at creation time. Like com.android.contacts does.

**Comment by Viish** [comment]
I have added in feature/kotlin_rewrite branch a setting to let the user choose between default sync account and app sync account.
However I won't add a dropdown with the list of all available sync accounts.

**Comment by brianjmurrell** [comment]
> setting to let the user choose between default sync account and app sync account.

I assume _app sync account_ is the Linphone built-in address book.  Is _default sync account_ the contacts from a non-linphone account defined in _Settings_->_Accounts_ then?  If so, there can be many accounts in there.  The Google account will be a constant, but one can have their own carddav server and use, say, [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) to manage those contacts.

So with more than just the Google account, how is _default sync account_ defined, as Linphone-android knows it?

**Comment by 532910** [comment]
> how is default sync account defined

Yep, Sylvain, could you clarify, what is "default sync account" and where is it configurable?

**Comment by Viish** [comment]
Ok after multiple headaches I finally found a decent solution.

I revert my previous changes and now when you save a contact it will ask you where to store it.
Only I don't have the same possibilities as the native app (as I'm not native and don't have the GET_ACCOUNTS_PRIVILEGED permission), so if a third party app (like CardDAV) doesn't make it's account "user visible", I can't use it.
For example on my phone this means I can't save it in my CardDAV account, only local device, Linphone, Google and Samsung accounts.

**Comment by brianjmurrell** [comment]
Is that (the CardDAV account issue) a problem with the CardDAV sync tool you are using that needs to be reported upstream or is that tool's behaviour in this regard accepted and acceptable?

It seems that if other account sync tools can be made user visible, why can't your CardDAV sync tool, yes?

**Comment by 532910** [comment]
And what is the problem to require `GET_ACCOUNTS_PRIVILEGED`?

**Comment by brianjmurrell** [comment]
> Only I don't have the same possibilities as the native app (as I'm not native and don't have the GET_ACCOUNTS_PRIVILEGED permission), so if a third party app (like CardDAV) doesn't make it's account "user visible", I can't use it.

This does not appear to be a problem with [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) fortunately.  I was able to save a contact to my Owncloud CardDAV instance from Linphone using the [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) connector.

Interestingly it shows in Linphone-android in both the general contacts list and the Linphone contacts list.  Is there any way to suppress the latter?  I'm really only interested in the general contacts list.

**Comment by Viish** [comment]
> Is that (the CardDAV account issue) a problem with the CardDAV sync tool you are using that needs to be reported upstream or is that tool's behaviour in this regard accepted and acceptable?
It seems that if other account sync tools can be made user visible, why can't your CardDAV sync tool, yes?

Indeed that is an issue with my CardDAV app, but I guess it won't be the only one with the issue...

> And what is the problem to require GET_ACCOUNTS_PRIVILEGED?

As for all "privileged" permissions, they are only granted to system apps (apps that are part of the firmware).

> Interestingly it shows in Linphone-android in both the general contacts list and the Linphone contacts list. Is there any way to suppress the latter? I'm really only interested in the general contacts list.

I'm not sure I understand. Can you attach a screenshot?

**Comment by 532910** [comment]
Is `GET_ACCOUNTS` not enough?

**Comment by Viish** [comment]
> Is GET_ACCOUNTS not enough?

No it's not: https://developer.android.com/about/versions/oreo/android-8.0-changes.html#aaad

And newChooseAccountIntent method doesn't work either as it asks user if it wants to create a new account (can't be removed) which can be disabled by the account provider (in this case my CardDAV app) which makes the activity return without allowing me to select it and make it visible...

**Comment by brianjmurrell** [comment]
> I'm not sure I understand. Can you attach a screenshot?

![Screenshot_20200820-085159](https://user-images.githubusercontent.com/559317/90772922-31c95680-e2c3-11ea-895b-852319224687.jpg)

I added _House Phones_ to my Owncloud CardDAV account, not my Linphone account.  It does appear also in the general contact list (to the left of the linphone contact list) so it was added to the Owncloud CardDAV server successfully.  It just seems it **also** got added to the Linphone address book however, which I don't want to happen.  Frankly I'd be tickled to be able to just disable the Linphone address book entirely as it's just another point of added confusion for users.

**Comment by Viish** [comment]
Actually where you store the contact isn't related at all with what contacts are visible in the "Linphone" contacts list.
The linphone contact list only shows contacts with at least a SIP URI (or a contact with a phone number that is known to be linked to a sip.linphone.org account), that's all.

**Comment by brianjmurrell** [comment]
So it's more of a _filter_ on the device's contacts lists than an actual separate contact list?

**Comment by Viish** [comment]
> So it's more of a filter on the device's contacts lists than an actual separate contact list?

Exactly.

**Comment by brianjmurrell** [comment]
Can it be disabled?

**Comment by Viish** [comment]
No, but it should be the default only if you use a sip.linphone.org account. I just noticed it's not what happens in the kotlin rewrite, so I just fixed it.

**Comment by brianjmurrell** [comment]
Do I understand correctly that this change basically just means that when one opens the contacts screen the page that is opened when the circled button (below) is opened instead of the one that has the square around it?

![image](https://user-images.githubusercontent.com/559317/90793500-cc349480-e2d9-11ea-9d1d-379b420578b0.png)

**Comment by Viish** [comment]
Yes

**Comment by brianjmurrell** [comment]
I'd like to reopen this one.  Or perhaps I should open a new one?

In current Linphone-Android when I choose a thread from the SMS tab and then choose _Add to contacts_ from the _hamburger menu_ on the top right I can choose a contact to add to or I can create a new contact.

When I do the latter I am asked where I want to save it and I am only given the choice of my gmail.com account or _Linphone contacts_ (local to the phone I presume and gets wiped when the phone is wiped -- so a non-starter).

I don't recall how I was able to save to a CardDAV address book in https://github.com/BelledonneCommunications/linphone-android/issues/590#issuecomment-676599281 but however it was, it seems to be gone now.

Being only given the choice of my Google account or local to the phone is very limiting from a perspective of wanting to be in control of one's own data and not relying on a spy organization like Google (to whatever extent one can at least).  I suspect you empathize with this position @Viish.  :smile: You seem like a privacy advocate.

**Comment by Viish** [comment]
Hi @brianjmurrell,

> I suspect you empathize with this position

I do! With 6.0 release to come (currently in public beta on the play store, and a nightly build available on our website) you can easily configure CardDAV account(s) from the settings.
By the way we no longer ask for write contacts permission so it won't be possible anymore to save a contact to the native address book.

**Comment by brianjmurrell** [comment]
Installed 6.0 nightly.  I cannot seem to find where one sets their SIP account password.

FWIW, I configure linphone using a QR code which fetches a linphonerc file that does not have a password in it.  Pre-6.0 when this was done, Linphone then prompted the user for the password.  But even if it did not one could open the account settings and add the password.

I can't seem to find anything of the sort in this 6.0 version.  I would have thought it would be in _Manage account_ but not seeing it there even.

**Comment by brianjmurrell** [comment]
I did eventually get prompted for a password.  It took several (many by some standards) minutes for it to do that though.  I suspect quite a number of failed registration attempts.

But that doesn't answer the question of where the password setting is in this new UI.

But back to contacts, a couple of problems.
1. Before doing anything (trying to add CardDAV address book, etc.) I have **NO** contacts available at all.  Not even the ones in the address books that the _contacts_ app on the device sees.  Is this expected?
2. Trying to add a CardDAV addressbook, I get a _synchronization error_.

For 2, above, surely some hints would be in the debug log.  But I cannot seem to find where one enables debugging and/or uploads a debug log.

**Comment by Viish** [comment]
> Pre-6.0 when this was done, Linphone then prompted the user for the password. 

> I did eventually get prompted for a password. It took several (many by some standards) minutes for it to do that though. I suspect quite a number of failed registration attempts.

This should still be the case in 6.0. Please send logs so I can take a loot at what happened please.

> I can't seem to find anything of the sort in this 6.0 version. I would have thought it would be in Manage account but not seeing it there even.

Indeed there is no way to manually change the password now, except for the dialog prompt in auth failure case.

> I have NO contacts available at all.

Did you grant the READ_CONTACTS permission ?

> Trying to add a CardDAV addressbook, I get a synchronization error.

Please attach logs.

>  But I cannot seem to find where one enables debugging and/or uploads a debug log.

Share logs button is in Help (in the side menu) -> Troubleshooting page.

**Comment by brianjmurrell** [comment]
> Did you grant the READ_CONTACTS permission ?

I believe so.  When I look at App permissions for the app it says it has _Contacts_ permission under _Allowed_ and says it has accessed in the last 24h.  Other permissions like Microphone say last accessed with a timestamp that is within the last 2 hours.

I'll take a look through logs for some of the issues above.

**Comment by Viish** [comment]
Yes by default Linphone filters contacts to only show the ones with a sip.linphone.org SIP address.
You can change that using the filter button on the top right of the contacts screen (funnel icon).

**Comment by brianjmurrell** [comment]
Ahh.  I see.  So, changing the filter to _See all_ I am still just seeing 3 out of my hundreds of contacts.  I suspect those are the only 3 in my contacts.google.com (i.e. my gmail) account.  None of the other contact from any of the  [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) connector contacts are being shown as pre-6.0 releases did.

**Comment by brianjmurrell** [comment]
The problem with adding of a CardDAV addressbook is that it's not including the (i.e. Basic) authentication header with the `PROPFIND` query and failing once it gets the 401 response instead of retrying with the authorization header.

The [log](http://brian.interlinx.bc.ca/linphone-carddav-authentiation-failure.txt) is reporting:

```
2024-08-15 13:40:05:421 [org.linphone/liblinphone] ERROR [CardDAV] Authentication requested during CardDAV request sending, and username/password weren't provided
2024-08-15 13:40:05:421 [org.linphone/liblinphone] ERROR [CardDAV] CardDAV server to client sync failure: Authentication requested during CardDAV request sending, and username/password weren't provided
```

but a username and password were most certainly entered into the app.

**Comment by Viish** [comment]
> So, changing the filter to See all I am still just seeing 3 out of my hundreds of contacts. I suspect those are the only 3 in my contacts.google.com (i.e. my gmail) account. None of the other contact from any of the [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) connector contacts are being shown as pre-6.0 releases did.

Hum, that's weird.
Could you send me logs please?
I do also have DAVx⁵ but it works fine on my device.

> [CardDAV] Authentication requested with mode [BELLE_SIP_AUTH_MODE_HTTP_BASIC]

That's why sync doesn't work.
Currently we do not support BASIC auth out of the box, only Digest, Bearer or TLS.

**Comment by brianjmurrell** [comment]
> Could you send me logs please?

[log](http://brian.interlinx.bc.ca/linphone-only-gmail-contacts.txt)

TLS meaning what exactly in an authentication method context?  Basic only if the URL is `https`?

The connection to the CardDAV service was with TLS/`https`.

**Comment by Viish** [comment]
Indeed it doesn't load more than 5 entries, weird. I'll let you know when I'll have figured it out.

> TLS meaning what exactly in an authentication method context?

Certificate based. You authenticate yourself by sending a certificate that is validated by the other end.

**Comment by brianjmurrell** [comment]
> Certificate based. You authenticate yourself by sending a certificate that is validated by the other end.

Ahhh.  Right.  OK.

Is there a reason not support Basic authentication over TLS?

**Comment by brianjmurrell** [comment]
So is this a bug that needs fixing or will Linphone never support Basic auth. for CardDAV?

**Comment by Viish** [comment]
This isn't really a bug but yes, Linphone won't support BASIC auth (CardDAV or other) in 6.0 release.

Since you're using a SabreDAV based server, you can easily enable Digest instead of BASIC.

**Comment by brianjmurrell** [comment]
> Since you're using a SabreDAV based server, you can easily enable Digest instead of BASIC.

You might think.  Googling for instructions on how to enable Digest instead of Basic on NextCloud turns up nothing.  [Asking in their user forums](https://help.nextcloud.com/t/enable-digest-authentication-in-addition-to-basic/200889) has been silent so far.

Even though NC is SabreDAV based, maybe they have not exposed any ability to change the authentication method.

Having to always/only use Digest might be a hurdle for a lot of your users (that want to use CardDAV at least).

But all of this really makes me wonder why Linphone-Android needs to have it's own contacts handler client.  Why don't you just punt to another (i.e. contacts) app on the device (that already is talking to all of the address books on the device) like so many other apps do?

My e-mail client doesn't have it's own contacts handler for example.

**Comment by Viish** [comment]
> But all of this really makes me wonder why Linphone-Android needs to have it's own contacts handler client

Linphone on Android doesn't (as long as user grants contacts permission). 
On Desktop a bit more (like thunderbird app offers CardDAV sync for example).

**Comment by brianjmurrell** [comment]
So, in 6.0 on Android, if the user grants contact permission, should the choosing _Conversation info_ > _Add to contacts_ from the hamburger menu in a chat be bringing up the Linphone _New contact_ dialog or should it be asking me which contacts app I want to use to add the contact?

**Comment by Viish** [comment]
No, 6.0 will always save the contact internally. The only setting that is missing from current 6.0 beta is to choose if the newly added contact will be added to the CardDAV synchronized friend list or not.

**Comment by brianjmurrell** [comment]
But earlier I asked:

> … why Linphone-Android needs to have it's own contacts handler client. Why don't you just punt to another (i.e. contacts) app on the device (that already is talking to all of the address books on the device) like so many other apps do?

To which you answered:

> Linphone on Android doesn't (as long as user grants contacts permission).

which you seem to be then contradicting in the previous coimment.

So I'm still left wondering why Linphone, **on Android** needs any kind of internal contact storage/handling at all.  Why not just use Android's contact handling exclusively and leave all of the configuration, etc. of addressbooks to Android and the apps that it has that are focused thoroughly on contact handling?

**Comment by Viish** [comment]
> which you seem to be then contradicting in the previous coimment.

I don't see the contradiction. Linphone doesn't need any contacts sync mechanism as long as you grant the READ_CONTACTS permission, but if you don't it's nice to still be able to have contacts stored/synchronized.

> So I'm still left wondering why Linphone, on Android needs any kind of internal contact storage/handling at all. Why not just use Android's contact handling exclusively and leave all of the configuration, etc. of addressbooks to Android and the apps that it has that are focused thoroughly on contact handling?

Because there are many users that don't want to grant the READ_CONTACTS (and even less the WRITE_CONTACTS) permission. Because you may just want to create a Linphone contact for the few other users you know that can be called through SIP and don't want your whole addressbook. Because in a corporate environment your IT guy forces your contact list. 
If you give the READ_CONTACTS permission you will have your native addressbook and don't need to configure anything, you'll just have to create contacts in your contacts app, that's all.

**Comment by Viish** [comment]
> None of the other contact from any of the [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage) connector contacts are being shown as pre-6.0 releases did.

I checked and unless you edited your config file / app code to have either `[app] fetch_contacts_from_default_directory=0` or `corePreferences.fetchContactsFromDefaultDirectory = false` (default value is true), there is no reason the 6.0 wouldn't load contacts like your 5.2 did.

**Comment by brianjmurrell** [comment]
I've rebuilt and installed 9ec927c0c and looking at the config as displayed in the _Troubleshooting_ > _Show configuration_ (which is a great troubleshooting feature BTW, but it could use a search function :smile:) and I don't have `fetch_contacts_from_default_directory` in `[app]` at all.  I also don't touch `corePreferences.fetchContactsFromDefaultDirectory` anywhere.

But I'm still not seeing any difference in contact behaviour:
1. [still only have 3 contacts](https://github.com/BelledonneCommunications/linphone-android/issues/590#issuecomment-2292223808)
2. Adding new contacts is still using Linphone's contact handler.
3. Can't use Linphone's built-in CardDAV due to it requiring Digest authentication and I can't find any docs on how to switch from Basic to Digest in NextCloud.

**Comment by Viish** [comment]
> still only have 3 contacts

If you haven't `fetch_contacts_from_default_directory=0` then it's expected because nothing has changed in the contacts loader. However the same Android DB is used in 5.2.X version of Linphone-android, so I don't see how it could have been different in a previous version.

> Adding new contacts is still using Linphone's contact handler.

Expected as well, and will keep being this way as I explained previously. The only thing that's new is that you can choose if you save a new contact in Linphone internal friend list or in a given CardDAV one (if you configured one) so your newly added contacts will be synchronized (unless your CardDAV account is read only of course).

> Can't use Linphone's built-in CardDAV due to it requiring Digest authentication and I can't find any docs on how to switch from Basic to Digest in NextCloud.

That's sad. BASIC auth is really lame as it requires the server to keep your password in clear text somewhere...
You might want to check out [Baikal](https://sabre.io/baikal/) that's made by SabreDAV guys and offers the auth method choice. At least it may give you/Nextcloud guys a hint on how to enable Digest auth.

**Comment by brianjmurrell** [comment]
> You might want to check out Baikal

That is not going to be a replacement for everything that NextCloud does, which is a **lot** more than just DAV services.

But bottom line here is that 6.0 is not usable for me as it is.  It has no access to all of my contacts.  I am not going to be re-entering all of my contacts into Linphone just because it refuses to connect to either my phone's local contacts or even a CardDAV server (that doesn't have Digest authentication).  And frankly, having to add CardDAV addressbooks to Linphone specifically when my phone already has access to those CardDAV contacts is pretty much a non-starter also.

IMHO, Linphone (on Android) needs to give up this idea that it needs to reinvent contact handling and addressbooks and just use the contact handling provided by Android.

At least 5.2 could see my phone's contacts even if adding new ones was (quite! as documented in this ticket) cumbersome.

**Comment by Viish** [comment]
As I already said, there's no reason that 6.0 wouldn't be able to import your contacts as 5.2 did as the SQL query in Android's address book is the same.
Could you make sure that 5.2.5 is still able to read your contacts?

**Comment by brianjmurrell** [comment]
Oh man.  Never mind me.  I was being a total dumb-ass.

I am testing this new Linphone on a test/spare phone and forgot that I'd recently factory reset it and had not re-configured DAVx⁵.  After having done that, I am now seeing all of my NextCloud contacts.

My apologies for being such a dumb-ass about all of this.

I do still think requiring Digest authentication for the CardDAV connectivity is going to be a bit of a hurdle.  Since I have been unable to add a CardDAV addressbook it's not yet clear to me if more than one can be added.  I suspect at least a few people probably have more than one CardDAV addressbook.  I have one for personal contacts and one I share with my family for family contacts, for example.

**Comment by Viish** [comment]
> Since I have been unable to add a CardDAV addressbook it's not yet clear to me if more than one can be added.

Yes you can add as many as you need.

> Oh man. Never mind me.

Glad you found the issue.
