### ISSUE TITLE
Android io error when connecting to sip server

### ISSUE THREAD

**Issue by rsiwady29** [BelledonneCommunications/linphone-android#6]
Hello! I´m using linphone for android (downloaded from the playstore).  I keep getting an error: **"io error"** when trying to connect to a freeswitch sip server. Same server is used in an ios app and it works perfectly. I'm in a wifi network using ipv6. I've already tried connecting with ipv6 enabled and disabled from within the application. 

I'm also getting the same issue when using lib linphone on an android app made from scratch. I can provide linphonerc configurations if needed.

Anyone out here know what the issue might be?

**Comment by DatBewar** [comment]
Hello, thanks you for this report, we will investigate.

**Comment by DatBewar** [comment]
Do it works with an Linphone sip account ?

**Comment by rsiwady29** [comment]
Just created an account in https://www.linphone.org/free-sip-service.html and tested with those credentials. I'm still getting the same issue.

**Comment by DatBewar** [comment]
Can you give some logs of this problem please?

**Comment by gled-rs** [comment]
Did you checked that the DNS resolution of your server's name is going well ?

Had some issues with ipv6 nameservers in the past.

**Comment by jelenadj** [comment]
@rsiwady29 Are you on VPN? @DatBewar I can't connect on (non-linphone) SIP server using Android Linphone app while I am on VPN, it works works only if VPN is not turned on, otherwise getting "network error"/503. I am using latest app version (3.2.4) from the PlayStore. iOS app works without any issues, no matter is VPN turned on or not.
When I try to connect on Linphone server, after entering my credentials on "Assistant" view, I am getting error "Failed to query the server. Please try again".
Other apps on the same Android phone and network works without issues, and used VPN server is strong one.

**Comment by jehandelalune** [comment]
Hi,

Linphone finds the DNS servers to use from the android system properties.
Unfortunately it appears that these are not updated by the system when a VPN is
used.
This is documented here:

https://code.google.com/p/android/issues/detail?id=177536

Until we find (or google provides) a more reliable solution accessible in native
language, I invite you to use  LinphoneCore.setDnsServer() method in order to
explicitey set the dns servers to use:

http://www.linphone.org/docs/liblinphone-javadoc/org/linphone/core/LinphoneCore.html#setDnsServers%28java.lang.String[]%29

The list of servers can be obtained with java code from application using:
ConnectivityManager mgr = 
Context.getSystemService(Context.CONNECTIVITY_SERVICE);

mgr.getLinkProperties(mgr.getActiveNetwork()).getDnsServers()

These are returned as a list of InetAddress objects.

https://developer.android.com/reference/android/net/LinkProperties.html#getDnsServers%28%29

DNS servers shall be set each time a new network is found, that is each time the
app is about to call LinphoneCore.setNetworkReachable(true);

Best regards,

**Comment by preetamfrejun** [comment]
are there any resolutions. I am facing the same issue.
