### ISSUE TITLE
Could not find org.linphone:linphone-sdk-android:4.2.

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#609]
I cloned the project and started build gradle 

i am getting this error:

Could not find org.linphone:linphone-sdk-android:4.2

**Comment by StarkGOD024** [comment]
I have this problem too.
I get the latest version sdk aar file from http://www.linphone.org/technical-corner/liblinphone,but this released version is 4.0.1,not 4.2,when I put into this project,obviously,loss some Class files and some methods,I feel very troubled because I don't know how to compile the latest sdk souce code.

**Comment by Viish** [comment]
4.2 SDK can be found in our releases maven repository : http://linphone.org/releases/maven_repository/org/linphone/linphone-sdk-android/
4.2+ SDK can be found in our snapshots maven : http://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/

**Comment by ArjunHandeVerifone** [comment]
The problem for me was the sample and the app on git repo mentions repository url as https but it was actually http. Adding below lines fixed it.
maven {
        url "http://linphone.org/releases/maven_repository"
    }

**Comment by Viish** [comment]
For information, it should work also in https (it does at least where I am).
Also this is the legacy maven repository, the new one is https://linphone.org/maven_repository/ and can also be accessed either by http or https.
