### ISSUE TITLE
Double ring tones

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#625]
Unless I disable Settings->Call->Use device ringtone, when a call comes in, I get both my device's ringtone as well as one presumably built into linphone.  I would think enabling this option should disable the built-in one.

**Comment by Viish** [comment]
Use device ringtone silences the Core's ringtone to instead use an Android Media Player to play the device ringtone.
If with this setting enabled you have 2 ringtones it means the problem is the Core hasn't been silenced.
Could you attach the content of your device .linphonerc file please ?
Command is adb shell run-as org.linphone cat files/.linphonerc (if you use debug APK it should be org.linphone.debug instead).
Thanks.

**Comment by brianjmurrell** [comment]
```bash
$ adb shell run-as org.linphone cat files/.linphonerc
run-as: package not debuggable: org.linphone
```

**Comment by Viish** [comment]
Arf...
Can you attach your devices logs ? (clear them before reproducing please)

**Comment by brianjmurrell** [comment]
I don't seem to be able to reproduce this now.
