### ISSUE TITLE
If you disable video  on one side of a call, video is getting paused on both  

### ISSUE THREAD

**Issue by lucifer161995** [BelledonneCommunications/linphone-android#663]
when i call 
CallParams params = core.createCallParams(call);
params.enableVideo(false);
call.update(params);

video from both side is getting paused and unable to resume when i press enable video

**Comment by Viish** [comment]
This is expected: If you remove the video capability of the call, video stops from both side.
You can enable it back by doing the same thing (with true instead of false).
If you want video in only one direction, you can use:
```
core.enableVideoCapture(false);
core.enableVideoDisplay(false);
```
to disable locally the capture or the display. However toggling this settings won't notify the remote.

**Comment by Irfanulhaq1991** [comment]
@Viish These has no effect during call as per documentation. Could you please provide tell how could the  video from side disable or in the how can we do unidirectional video call.
