### ISSUE TITLE
Linphone Android Lime

### ISSUE THREAD

**Issue by crontab888** [BelledonneCommunications/linphone-android#718]
Hi,

Just built latest Linphone for Android with LIME enabled:

cmake -DENABLE_GPL_THIRD_PARTIES=YES -DENABLE_NON_FREE_CODECS=YES **-DENABLE_LIME=YES** -DENABLE_AMRNB=YES -DLINPHONESDK_PLATFORM=Android ..

After installing the apk on a device I simply cannot find the LIME setting to enable it, sniffing the MESSAGE traffic, all is cleat text, hence it is not on by default.

I am a bit confused what am I doing wrong here; I am sure that I used the right .aar files as other options that I enabled( amr for ex) are there.

I remember in past Linphone Android it was there, I installed the GPlay version as well and it is not there either.
Looking trough the directory, lime is present, at least as a folder.

Anything wrong happened with LIME for Android?

**Comment by Viish** [comment]
Hi,

Indeed we don't use anymore the 'old' LIME.
Instead we switched to LIME X3DH that allows us to do end-to-end encryption.
They are mutually incompatible, that's why we disable the old one by default in the SDK.

For the app, we've also removed the setting but you can still call Core.enableLime(LimeState state) even if it's deprecated.

Cheers,

**Comment by czaviar** [comment]
Is there any chance to re-eanble the old Lime in the current version of SDK and app ? Or the only one to support it was Linphone 4.0.1 ?
