### ISSUE TITLE
Error in receiving Video on H264 on Android 5.1.1

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-android#738]
Dear Team,

While video calling on H264 codec on android 5.1, my hard phone is able to send video but unable to receive video. Green screen appears at my end whereas the other party getting my video perfectly. 

Attached the video of the problem.

![videocallingissue_h264_android_5_1](https://user-images.githubusercontent.com/5437700/62847067-cf259e00-bcf1-11e9-99ce-5878c0dd7512.png)

**Comment by Viish** [comment]
Hi,
Can you attach logs from the devices with the green video issue please ?

**Comment by amit1576** [comment]
Hi Viish,

Please find attached logs from device.  Please check and suggest what can be done to solve this.

**The Log stated followings :**

**I/CoralUC ( 2232): [Manager] Android >= 5.1 we disable the download of OpenH264
I/CoralUC ( 2232): H264Helper setH264Mode  MODE_AUTO - Mode = Auto
I/CoralUC ( 2232): H264Helper setH264Mode  MODE_AUTO 1 - Mode = Auto
I/CoralUC ( 2232): H264Helper Openh264 disabled on the project, now using MediaCodec
E/CoralUC ( 2232): Cannot enable/disable unknown filter [MSOpenH264Dec] on factory [0xb78b2ea0]
E/CoralUC ( 2232): Cannot enable/disable unknown filter [MSOpenH264Enc] on factory [0xb78b2ea0]
E/CoralUC ( 2232): Cannot enable/disable unknown filter [MSMediaCodecH264Dec] on factory [0xb78b2ea0]
E/CoralUC ( 2232): Cannot enable/disable unknown filter [MSMediaCodecH264Enc] on factory [0xb78b2ea0]
I/CoralUC ( 2232): H264Helper setH264Mode - Mode = Auto**


[Message.txt](https://github.com/BelledonneCommunications/linphone-android/files/3495467/Message.txt)

**Comment by Viish** [comment]
Hi,

What SIP client do you use to call your device ?

From the logs, the decoder fails to decode the incoming video stream, either because it is wrongly formatted by the other end or because the implementation of the H264MediaCodec on this particular device is crappy:
I/CoralUC ( 2232): MediaCodecDecoder: new paramter sets received
E/H264_DEBUG(  185): ERROR: SLICE_HEADER
I/H264_DEBUG(  185): display width 640, display height 480
I/vpu_api (  185): info_change break
I/vpu_api (  185): get info change out xxxx
D/H264_DEBUG(  185): found resync point  
E/H264_DEBUG(  185): found mismatch decode length: set       5641 dec 1500259328E/ROCKCHIP_VIDEO_DECCONTROL(  185): OMX_IndexParamdescribeColorFormat get 
E/ROCKCHIP_OSAL_Android(  185): OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
E/OMXNodeInstance(  185): getParameter(31:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
W/ACodec  ( 2232): do not know color format 0x0 = 0
E/OMXNodeInstance(  185): getConfig(31:rk._decoder.avc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)

**Comment by amit1576** [comment]
Hi Viish,

**I am using Linphone Desktop on the other end.** 

When i am using two Linphone Desktop version on both end / or Linphone Desktop at one end or any sip phone at other end,  the video calling is working fine. In-fact same app working fine on Android Mobile Phone.

But when I load app in device this green screen appears in video calling.

One more input the device of which i have sent you logs, will work on H264 Codec with other sip application.

**Comment by Viish** [comment]
Ok so it means the problem is the media codec implementation of your device.
5.1.1 was one of the first (if not the first) version of Android to have MediaCodec API, and each device manufacturer has the possibility to make it's own implementation of the codec through this API.
We already seen some other devices that do it badly.

**Comment by amit1576** [comment]
Hi @Viish ,

**So what can be done.** 

If Android 5.1.1 is the issue, for testing i had also tried on Android 6, Android 7.1.2(Hard Devices) but same Green Screen Appear issue is there.

But the Linphone version 4.0.1 is working fine on every device.

Can you suggest any workaround. Because i got stuck badly.

**Comment by Viish** [comment]
What do you mean Linphone 4.0.1 is working ? So what isn't working ?
When you tried other Android versions, was it on the same hardware or another device ? And with linphone-desktop as the remote end ?

**Comment by Viish** [comment]
I don't reproduce the issue.
What are the devices you tried ?

**Comment by Viish** [comment]
Also, does it happen Android to Android ?

**Comment by amit1576** [comment]
Hi @Viish ,

i have tried on Akuvox R48. For your reference i have share you the website link.

**http://www.akuvox.com/pro3/VP-R48G.shtml**

Yes same issue comes when i calling from Android to Android.

**Comment by amit1576** [comment]
Hi @Viish ,

Any feedback.

**Comment by Viish** [comment]
Please attach logs for another device (for example the one with Android 7.1.2)

**Comment by amit1576** [comment]
Hi @Viish 

Unfortunately i can not export logs from that device right now.  But issue is same as 5.1.1.

**Comment by Viish** [comment]
As I don't reproduce the issue I won't be able to do much without logs or even the device.
If you really need this problem to be solved, please contact our sales (sales@belledonne-communications.com) department that will give you a quotation for either a support or dev-assist contract.

**Comment by amit1576** [comment]
Hi @Viish ,

As discussed with you earlier, linphone android app(Video Receiving) is not working on above mentioned android devices. For experiment i tried the same android app on **"Tinker board SBC"**, where i have the possibility to customize android. I had found same video receiving problem on **"Tinker board SBC"** as well, then i found that Media Codec API was disabled by defaults, which causing Video receiving problem as linphone uses Media Codec API. As soon as i enabled them the Video Receiving problem got resolved on **"Tinker board SBC"**. I suspect my other device also has Media Codec Disabled.

**But now one another observation, The Video is receiving only at QVGA(320*240). No matter sender sending video on higher resolutions. Where as Android Mobile to Mobile no such issue ever observed.  **

Request you to help me out.

For reference i have attached two file. one is on Samsung Phone while other is on **"Tinker board SBC"**.



![App on samsung mobile](https://user-images.githubusercontent.com/5437700/63206917-4b95f380-c0db-11e9-9c97-c9cb48afb22e.jpg)
![App on Tinker board](https://user-images.githubusercontent.com/5437700/63206918-4c2e8a00-c0db-11e9-9909-0ca612a5f225.jpg)
