### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by chandrasekhar109** [BelledonneCommunications/linphone-android#750]
Hi Team,
Recently I am facing registration issue in my Linphone application.I used 3.3.2 version at that time.
If i put UDP as Transport type  registration not getting success.If changed it to TCP  registering success immediately.but this is not suitable to  our requirement.I changed mobile network also.But didn't worked.Can anyone please tell me solution for this.

**Comment by Viish** [comment]
Hi,
UDP isn't broken since 3.3.2, however we've added some features in the library that generates slightly bigger packets, so it increases the risk of a lost UDP packet.
Anyway we strongly advertise against UDP for SIP (you can read more here: https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Good%20practices%20for%20using%20SIP/), but if you need you can contact our sales department (sales@belledonne-communications.com) to have a quotation for either support or dev-assist.
Cheers,
