### ISSUE TITLE
which android version can support h265?

### ISSUE THREAD

**Issue by andyleeqd** [BelledonneCommunications/linphone-android#796]
which android version can support h265?

**Comment by Viish** [comment]
This pages says that H265 is available since Android Lollipop (5.0):
https://developer.android.com/about/versions/lollipop.html#Camera
https://developer.android.com/guide/topics/media/media-formats#video-codecs

But actually that depends on the device and whether or not they implement the H265 MediaCodec API.

**Comment by andyleeqd** [comment]
sorry, I mean which linphone version for android can support h265

**Comment by Viish** [comment]
If you take a look at the CHANGELOG file you'll see the answer is 4.1.0.

**Comment by andyleeqd** [comment]
I downloaded 4.1.0 android version, but only support h264, no h265 option

**Comment by Viish** [comment]
This means your device isn't compatible

**Comment by andyleeqd** [comment]
my phone chipset is qualcomm 8953, can support h265, is there have relevances with android system version? my phone android version is 7.1

**Comment by Viish** [comment]
Yes it depends on the Android version.
Please enable & attach debug logs
