### ISSUE TITLE
Linphone Android SDK 4.3+ disable extra features

### ISSUE THREAD

**Issue by shadowwalkersteam** [BelledonneCommunications/linphone-android#885]
I'm using linphone android sdk 4.3, i added the sdk in my project via gradle. 
`implementation "org.linphone:linphone-sdk-android:4.3+"`
I just want outgoing voice call, currently the app size is very large, i want to disable video call and other features which are not required. Can anyone help me how i can disable the features from gradle file?

**Comment by shadowwalkersteam** [comment]
I see you have reduced your apk size on the Playstore, I cloned the same repository and generated the apk but my apk size is still 38mb

**Comment by Viish** [comment]
Hi,
Indeed our AAR is quite large because it contains native libraries for 4 architectures.
With the 4.2 release we use the apk bundle mode which let Google creates an apk with only the required architecture that's why the size decreased. 
If you want you can either use the no-video AAR that is a bit less heavy or build your own AAR (see the Readme file in linphone-sdk repository)
