### ISSUE TITLE
Restart phone its shows Fatal Exception: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by mehulp89** [BelledonneCommunications/linphone-android#917]
While restarting android phone it shows me below error 

Fatal Exception: android.app.RemoteServiceException

> Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=linphone_notification_service_id pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 category=service vis=SECRET)

Can you share the reason behind it? Had it been handled in the library?

**Comment by Viish** [comment]
Did you forgot to set `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` ?
Or maybe you edited the code some way and you don't create the notification channels.
Or you are using a very old version of the code.

**Comment by mehulp89** [comment]
This permission is already set <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />.
And we are using your library which is available on Github. 

`Or maybe you edited the code some way and you don't create the notification channels.
`
No, we didn't change anything in it. 

`Or you are using a very old version of the code.
`
How can we identify old version or new version? 

Thanks

**Comment by Viish** [comment]
> And we are using your library which is available on Github.

You issue isn't due to our SDK, it's a pure Android app problem.
When the phone boots the app starts automatically. For it not to be killed right away we display a service notification. You problem is the notification channel used for this notification doesn't exists (it's the same channel as for call notifications for example).

> How can we identify old version or new version?

Do a `git describe` in your local copy of the repository. Also you can check version number or version code.
