### ISSUE TITLE
crash when accept to call

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-android#934]
hi i used liblinpone 4.3 
Sometimesthe beep sound of Outgoing Ringing  didn't played and   when destination user accept to call , my phone crashed ! 

[crash.txt](https://github.com/BelledonneCommunications/linphone-android/files/4280897/crash.txt)

**Comment by Viish** [comment]
You an OpenSLES error:
```
2020-03-03 14:29:20.323 27684-28144/? E/ linphone: [OpenSLES] Error 9 while realizing output sink
2020-03-03 14:29:20.324 27684-28144/? E/ linphone: [OpenSLES] Couldn't init OpenSLES sink
```
I believe the destruction of the filter crash because of this (even if it shouldn't).

By the way, it seems your app using our SDK (https://play.google.com/store/apps/details?id=mobi.mmdt.ottplus&hl=en) **isn't respecting the GPL license** (I couldn't see any mention of it anywhere). Please either update your app & website to reflect it or buy a proprietary license from Belledonne Communications (sales@belledonne-communications.com). With the license comes 6 months support for any issues (like this one).

**Comment by krv372** [comment]
ok

**Comment by Viish** [comment]
Karim, no need to remove everything from this issue and your profile that could incriminate you, github (and internet) keep everything...
