### ISSUE TITLE
Leading 0 is not removed when using country prefix

### ISSUE THREAD

**Issue by bjo81** [BelledonneCommunications/linphone-android#940]
While using linphone with sipgate and 49 as country prefix, linphone extends it to +490xyz instead of being stripped to +49xyz

**Comment by Viish** [comment]
How many digits does your phone number have?
Our current setup allows up to 12 digits per phone number, which seems to match the information I could find online.
This means the leading 0 will be stripped only if the total length of the phone number exceeds 12.

**Comment by bjo81** [comment]
It's a common german mobile number consisting of 11 digits.

**Comment by Viish** [comment]
Sadly we can't do much about it.
In Germany it is legal to have a phone number with 12 digits.
So we can't assume that if a number starts with a 0 and has a length of 11 we must remove it before inserting the international prefix because +490xyz is valid.

**Comment by stiltgit** [comment]
In most parts of Europe, including Germany, there exist no telephone numbers starting with a leading zero. 
One leading zero followed by digits 1-9 is the national trunk prefix
Two leading zeros is the international trunk prefix 
There are no local telephone numbers at all starting with digit 0 in Germany
+490xyz is under no circumstances valid.

**Comment by bjo81** [comment]
@stiltgit Thanks for pointing this out. No clue why @Viish still believes that +490xy could be a valid prefix.

**Comment by grthr** [comment]
> @stiltgit Thanks for pointing this out. No clue why @Viish still believes that +490xy could be a valid prefix.
Can we therefore reopen this?

**Comment by bjo81** [comment]
Some days ago I stumbled upon a number where +490 was valid, a 00800-number. But I think this is the only case.

**Comment by grthr** [comment]
true, but 00800 is international toll free number. [According to German Federal Network Agency](https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/InternationaleRufnummern/00800/00800.html) it works like an international number. The prefix `+` is valid instead of `00`. There is no special handling needed for `00800` because it can be treated like any other international number (e.g. replace `00` by `+`)
